// packages/solid/src/components/form/switch/switch.tsx
import { type JSX, splitProps } from "solid-js";
import { Switch as KSwitch } from "@kobalte/core/switch";
import { cn } from "../../../lib/cn";

/**
 * Switch — Solid port built on Kobalte's Switch primitive.
 *
 *   <Switch checked={value()} onChange={setValue} />
 *
 * Kobalte supplies controlled/uncontrolled state (`checked` /
 * `defaultChecked`), the `name` / `value` hidden input for native form
 * submission, keyboard (space), and ARIA (role="switch",
 * aria-checked). Theming via --zen-* tokens; size is a record-keyed
 * variant.
 */

export type SwitchSize = "sm" | "md" | "lg";

export type SwitchProps = {
  size?: SwitchSize;
  class?: string;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  disabled?: boolean;
  required?: boolean;
  name?: string;
  value?: string;
  /** Optional inline label rendered to the right of the switch. */
  label?: JSX.Element;
};

const TRACK_SIZES: Record<SwitchSize, string> = {
  sm: "h-4 w-7",
  md: "h-5 w-9",
  lg: "h-6 w-11",
};
const THUMB_SIZES: Record<SwitchSize, string> = {
  sm: "h-3 w-3 data-[checked]:translate-x-3 translate-x-0.5",
  md: "h-4 w-4 data-[checked]:translate-x-4 translate-x-0.5",
  lg: "h-5 w-5 data-[checked]:translate-x-5 translate-x-0.5",
};

export const Switch = (props: SwitchProps) => {
  const [local] = splitProps(props, [
    "class",
    "size",
    "checked",
    "defaultChecked",
    "onChange",
    "disabled",
    "required",
    "name",
    "value",
    "label",
  ]);
  const size = () => local.size ?? "md";
  return (
    <KSwitch
      checked={local.checked}
      defaultChecked={local.defaultChecked}
      onChange={local.onChange}
      disabled={local.disabled}
      required={local.required}
      name={local.name}
      value={local.value}
      class={cn("inline-flex items-center gap-2", local.class)}
    >
      <KSwitch.Input />
      <KSwitch.Control
        class={cn(
          "peer inline-flex shrink-0 cursor-pointer items-center rounded-zen-full",
          "transition-colors",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zen-ring focus-visible:ring-offset-2",
          "data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
          "data-[checked]:bg-zen-primary bg-zen-muted",
          TRACK_SIZES[size()],
        )}
      >
        <KSwitch.Thumb
          class={cn(
            "block rounded-zen-full bg-zen-background shadow-md ring-0",
            "transition-transform",
            THUMB_SIZES[size()],
          )}
        />
      </KSwitch.Control>
      {local.label ? <KSwitch.Label class="text-sm">{local.label}</KSwitch.Label> : null}
    </KSwitch>
  );
};

// src/components/form/switch/switch.tsx
import * as React from "react";
import * as SwitchPrimitive from "@radix-ui/react-switch";
import { cn } from "../../../lib/cn";

/**
 * Switch — built on @radix-ui/react-switch.
 *
 *   <Switch checked={value} onCheckedChange={setValue} />
 *
 * Radix supplies controlled/uncontrolled state, name + value for form
 * submission, keyboard (space/enter), and ARIA (role="switch", aria-checked).
 * Theming via --zen-* tokens; size is a CVA variant.
 */

export type SwitchSize = "sm" | "md" | "lg";

export interface SwitchProps
  extends React.ComponentPropsWithoutRef<typeof SwitchPrimitive.Root> {
  size?: SwitchSize;
}

const TRACK_SIZES: Record<SwitchSize, string> = {
  sm: "h-4 w-7",
  md: "h-5 w-9",
  lg: "h-6 w-11",
};
const THUMB_SIZES: Record<SwitchSize, string> = {
  sm: "h-3 w-3 data-[state=checked]:translate-x-3 data-[state=unchecked]:translate-x-0.5",
  md: "h-4 w-4 data-[state=checked]:translate-x-4 data-[state=unchecked]:translate-x-0.5",
  lg: "h-5 w-5 data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0.5",
};

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitive.Root>,
  SwitchProps
>(({ className, size = "md", ...props }, ref) => (
  <SwitchPrimitive.Root
    ref={ref}
    className={cn(
      "peer inline-flex shrink-0 cursor-pointer items-center rounded-zen-full",
      "transition-colors",
      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zen-ring focus-visible:ring-offset-2",
      "disabled:cursor-not-allowed disabled:opacity-50",
      "data-[state=checked]:bg-zen-primary data-[state=unchecked]:bg-zen-muted",
      TRACK_SIZES[size],
      className,
    )}
    {...props}
  >
    <SwitchPrimitive.Thumb
      className={cn(
        "block rounded-zen-full bg-zen-background shadow-md ring-0",
        "transition-transform",
        THUMB_SIZES[size],
      )}
    />
  </SwitchPrimitive.Root>
));
Switch.displayName = SwitchPrimitive.Root.displayName;

export { Switch };
