// packages/solid/src/components/card/card.selectable.tsx
import { type JSX, splitProps } from "solid-js";
import { RadioGroup as KRadioGroup } from "@kobalte/core/radio-group";
import { cn } from "../../lib/cn";

/**
 * SelectableCard — radio-as-a-card pattern for onboarding "pick one"
 * questions (goal picker, plan picker, use-case picker). Solid port
 * built on Kobalte's RadioGroup.
 *
 *   <SelectableCardGroup value={goal()} onValueChange={setGoal}>
 *     <SelectableCard value="invoice" title="Send invoices" icon={<I />}>
 *       Bill customers and track payments.
 *     </SelectableCard>
 *     <SelectableCard value="track" title="Track expenses" icon={<E />}>
 *       Log receipts and categorize spending.
 *     </SelectableCard>
 *   </SelectableCardGroup>
 *
 * Kobalte handles exactly-one selection, full keyboard nav (arrows +
 * Home/End), and form submission semantics via a hidden radio input.
 *
 * API delta from the React (Radix) binding: the prop is `onValueChange`
 * on the React side; in Solid we use `onChange` to match Kobalte's
 * idiom across the rest of the binding. Both forms are accepted.
 */

export type SelectableCardGroupProps = {
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  /** Alias for onChange, for parity with the React `onValueChange` name. */
  onValueChange?: (value: string) => void;
  name?: string;
  disabled?: boolean;
  required?: boolean;
  orientation?: "horizontal" | "vertical";
  class?: string;
  children?: JSX.Element;
};

export const SelectableCardGroup = (props: SelectableCardGroupProps) => {
  const [local] = splitProps(props, [
    "value",
    "defaultValue",
    "onChange",
    "onValueChange",
    "name",
    "disabled",
    "required",
    "orientation",
    "class",
    "children",
  ]);
  return (
    <KRadioGroup
      value={local.value}
      defaultValue={local.defaultValue}
      onChange={(v) => {
        local.onChange?.(v);
        local.onValueChange?.(v);
      }}
      name={local.name}
      disabled={local.disabled}
      required={local.required}
      orientation={local.orientation}
      class={cn("zen-grid zen-gap-3", local.class)}
    >
      {local.children}
    </KRadioGroup>
  );
};

export type SelectableCardProps = {
  value: string;
  title?: JSX.Element;
  icon?: JSX.Element;
  /** Trailing badge slot (top-right) — typically a Badge component with
   *  "Most popular" / "Best value" / "5+ users" style copy. */
  badge?: JSX.Element;
  children?: JSX.Element;
  disabled?: boolean;
  class?: string;
};

export const SelectableCard = (props: SelectableCardProps) => {
  const [local] = splitProps(props, [
    "value",
    "title",
    "icon",
    "badge",
    "children",
    "disabled",
    "class",
  ]);
  return (
    <KRadioGroup.Item
      value={local.value}
      disabled={local.disabled}
      class={cn(
        "zen-group zen-relative zen-w-full zen-text-left",
        "zen-rounded-zen-md zen-border-2 zen-border-zen-border zen-bg-zen-background",
        "zen-p-4 zen-cursor-pointer zen-transition-colors",
        // hover (only when not selected and not disabled)
        "hover:zen-border-zen-muted-fg",
        // selected — primary ring + soft tint (Kobalte uses data-checked)
        "data-[checked]:zen-border-zen-primary data-[checked]:zen-bg-zen-primary-soft",
        // disabled
        "data-[disabled]:zen-cursor-not-allowed data-[disabled]:zen-opacity-50",
        "data-[disabled]:hover:zen-border-zen-border",
        "focus-within:zen-outline-none focus-within:zen-ring-2 focus-within:zen-ring-zen-ring focus-within:zen-ring-offset-2",
        local.class,
      )}
    >
      <KRadioGroup.ItemInput class="zen-sr-only" />
      <KRadioGroup.ItemControl class="zen-contents">
        {/* Top row: icon + title (+ optional badge) */}
        <div class="zen-flex zen-items-start zen-gap-3">
          {local.icon ? (
            <span
              aria-hidden
              class={cn(
                "zen-inline-flex zen-items-center zen-justify-center zen-flex-shrink-0",
                "zen-h-8 zen-w-8 zen-rounded-zen-sm",
                "zen-bg-zen-muted zen-text-zen-muted-fg",
                "group-data-[checked]:zen-bg-zen-primary group-data-[checked]:zen-text-zen-primary-fg",
              )}
            >
              {local.icon}
            </span>
          ) : null}
          <div class="zen-flex-1 zen-min-w-0">
            <div class="zen-flex zen-items-center zen-gap-2">
              {local.title ? (
                <KRadioGroup.ItemLabel class="zen-text-sm zen-font-semibold zen-text-zen-foreground">
                  {local.title}
                </KRadioGroup.ItemLabel>
              ) : null}
              {local.badge ? <span class="zen-ml-auto">{local.badge}</span> : null}
            </div>
            {local.children ? (
              <div class="zen-text-xs zen-text-zen-muted-fg zen-mt-1 zen-leading-relaxed">
                {local.children}
              </div>
            ) : null}
          </div>
        </div>

        {/* Top-right check indicator — only visible when selected. */}
        <KRadioGroup.ItemIndicator
          class={cn(
            "zen-absolute zen-top-2.5 zen-right-2.5",
            "zen-inline-flex zen-items-center zen-justify-center",
            "zen-h-5 zen-w-5 zen-rounded-zen-full",
            "zen-bg-zen-primary zen-text-zen-primary-fg",
          )}
        >
          <svg
            width="12"
            height="12"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="3"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden
          >
            <polyline points="20 6 9 17 4 12" />
          </svg>
        </KRadioGroup.ItemIndicator>
      </KRadioGroup.ItemControl>
    </KRadioGroup.Item>
  );
};

// packages/react/src/components/card/card.selectable.tsx
import * as React from "react";
import * as RadioGroupPrimitive from "@radix-ui/react-radio-group";
import { cn } from "../../lib/cn";

/**
 * SelectableCard — radio-as-a-card pattern for onboarding "pick one"
 * questions (goal picker, plan picker, use-case picker). Selectable
 * cards consistently outperform classic radio lists for these
 * questions: bigger tap targets, room for icon + description,
 * decision-feel rather than option-feel.
 *
 *   <SelectableCardGroup value={goal} onValueChange={setGoal}>
 *     <SelectableCard value="invoice" title="Send invoices" icon={<I />}>
 *       Bill customers and track payments.
 *     </SelectableCard>
 *     <SelectableCard value="track" title="Track expenses" icon={<E />}>
 *       Log receipts and categorize spending.
 *     </SelectableCard>
 *   </SelectableCardGroup>
 *
 * Built on Radix RadioGroup so:
 *   - exactly-one selection, native radio-group keyboard nav (arrows +
 *     Home/End), proper form submission semantics,
 *   - controlled (`value` + `onValueChange`) or uncontrolled
 *     (`defaultValue`) state,
 *   - `disabled` works per-item or at the group level.
 *
 * The underlying `<input type="radio">` is visually hidden (Radix's
 * RadioGroupItem renders a button — we wrap its label so the whole
 * card surface is the click target).
 */

const SelectableCardGroup = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root>
>(({ className, ...props }, ref) => (
  <RadioGroupPrimitive.Root
    ref={ref}
    className={cn("grid gap-3", className)}
    {...props}
  />
));
SelectableCardGroup.displayName = "SelectableCardGroup";

export interface SelectableCardProps
  extends Omit<
    React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Item>,
    "children" | "title"
  > {
  title?: React.ReactNode;
  icon?: React.ReactNode;
  /** Trailing badge slot (top-right) — typically a Badge with
   *  "Most popular" / "Best value" / "5+ users" style copy. */
  badge?: React.ReactNode;
  children?: React.ReactNode;
}

const SelectableCard = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Item>,
  SelectableCardProps
>(({ className, title, icon, badge, children, ...props }, ref) => (
  <RadioGroupPrimitive.Item
    ref={ref}
    className={cn(
      "group relative w-full text-left",
      "rounded-zen-md border-2 border-zen-border bg-zen-background",
      "p-4 cursor-pointer transition-colors",
      /* hover (only when not selected and not disabled) */
      "hover:border-zen-muted-fg",
      /* selected state — primary ring + soft tint */
      "data-[state=checked]:border-zen-primary data-[state=checked]:bg-zen-primary-soft",
      /* disabled */
      "disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:border-zen-border",
      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zen-ring focus-visible:ring-offset-2",
      className,
    )}
    {...props}
  >
    {/* Top row: icon + title (+ optional badge) + check indicator */}
    <div className="flex items-start gap-3">
      {icon ? (
        <span
          aria-hidden
          className={cn(
            "inline-flex items-center justify-center flex-shrink-0",
            "h-8 w-8 rounded-zen-sm",
            "bg-zen-muted text-zen-muted-fg",
            "group-data-[state=checked]:bg-zen-primary group-data-[state=checked]:text-zen-primary-fg",
          )}
        >
          {icon}
        </span>
      ) : null}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          {title ? (
            <span className="text-sm font-semibold text-zen-foreground">
              {title}
            </span>
          ) : null}
          {badge ? <span className="ml-auto">{badge}</span> : null}
        </div>
        {children ? (
          <div className="text-xs text-zen-muted-fg mt-1 leading-relaxed">
            {children}
          </div>
        ) : null}
      </div>
    </div>

    {/* Top-right check indicator — only visible when selected. */}
    <RadioGroupPrimitive.Indicator
      className={cn(
        "absolute top-2.5 right-2.5",
        "inline-flex items-center justify-center",
        "h-5 w-5 rounded-zen-full",
        "bg-zen-primary text-zen-primary-fg",
      )}
    >
      <svg
        width="12"
        height="12"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <polyline points="20 6 9 17 4 12" />
      </svg>
    </RadioGroupPrimitive.Indicator>
  </RadioGroupPrimitive.Item>
));
SelectableCard.displayName = "SelectableCard";

export { SelectableCard, SelectableCardGroup };
