// packages/solid/src/components/card/card.tsx
import { type JSX, splitProps } from "solid-js";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/cn";

/**
 * Card — generic surface primitive. Compound API for the common
 * Header / Content / Footer layout, every part opt-in.
 *
 *   <Card>
 *     <CardHeader>
 *       <CardTitle>Account</CardTitle>
 *       <CardDescription>Your billing + contact info.</CardDescription>
 *     </CardHeader>
 *     <CardContent>…</CardContent>
 *     <CardFooter><Button>Save</Button></CardFooter>
 *   </Card>
 */

const cardVariants = cva(
  "zen-rounded-zen-md zen-border zen-bg-zen-background zen-text-zen-foreground",
  {
    variants: {
      variant: {
        elevated: "zen-border-zen-border zen-shadow-zen-sm",
        outlined: "zen-border-zen-border",
        ghost: "zen-border-transparent",
      },
      padding: {
        none: "",
        sm: "zen-p-3",
        md: "zen-p-5",
        lg: "zen-p-6",
      },
    },
    defaultVariants: {
      variant: "outlined",
      padding: "none",
    },
  },
);

export type CardProps = VariantProps<typeof cardVariants> &
  Omit<JSX.HTMLAttributes<HTMLDivElement>, "class"> & {
    class?: string;
    children?: JSX.Element;
  };

export const Card = (props: CardProps) => {
  const [local, rest] = splitProps(props, ["class", "variant", "padding", "children"]);
  return (
    <div
      class={cn(cardVariants({ variant: local.variant, padding: local.padding }), local.class)}
      {...rest}
    >
      {local.children}
    </div>
  );
};

type SectionProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class"> & {
  class?: string;
  children?: JSX.Element;
};

export const CardHeader = (props: SectionProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div class={cn("zen-flex zen-flex-col zen-gap-1 zen-p-5 zen-pb-3", local.class)} {...rest}>
      {local.children}
    </div>
  );
};

type TitleProps = Omit<JSX.HTMLAttributes<HTMLHeadingElement>, "class"> & {
  class?: string;
  children?: JSX.Element;
};

export const CardTitle = (props: TitleProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <h3
      class={cn("zen-text-base zen-font-semibold zen-leading-tight zen-m-0 zen-text-zen-foreground", local.class)}
      {...rest}
    >
      {local.children}
    </h3>
  );
};

type ParagraphProps = Omit<JSX.HTMLAttributes<HTMLParagraphElement>, "class"> & {
  class?: string;
  children?: JSX.Element;
};

export const CardDescription = (props: ParagraphProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <p class={cn("zen-text-sm zen-text-zen-muted-fg zen-m-0", local.class)} {...rest}>
      {local.children}
    </p>
  );
};

export const CardContent = (props: SectionProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div class={cn("zen-p-5 zen-pt-0", local.class)} {...rest}>
      {local.children}
    </div>
  );
};

export const CardFooter = (props: SectionProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div
      class={cn("zen-flex zen-items-center zen-gap-2 zen-p-5 zen-pt-3 zen-border-t zen-border-zen-border", local.class)}
      {...rest}
    >
      {local.children}
    </div>
  );
};

export { cardVariants };

// packages/react/src/components/card/card.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/cn";

/**
 * Card — generic surface primitive. Compound API for the common
 * Header / Content / Footer layout, but every part is opt-in so you
 * can compose freely.
 *
 *   <Card>
 *     <CardHeader>
 *       <CardTitle>Account</CardTitle>
 *       <CardDescription>Your billing + contact info.</CardDescription>
 *     </CardHeader>
 *     <CardContent>…</CardContent>
 *     <CardFooter>
 *       <Button>Save</Button>
 *     </CardFooter>
 *   </Card>
 *
 * For "pick one of these options" / plan picker / goal picker patterns,
 * use the SelectableCard / SelectableCardGroup variant in
 * card.selectable.tsx — those add radio-group semantics + selected
 * styling on top of the base Card surface.
 */

const cardVariants = cva(
  "rounded-zen-md border bg-zen-background text-zen-foreground",
  {
    variants: {
      variant: {
        elevated: "border-zen-border shadow-zen-sm",
        outlined: "border-zen-border",
        ghost: "border-transparent",
      },
      padding: {
        none: "",
        sm: "p-3",
        md: "p-5",
        lg: "p-6",
      },
    },
    defaultVariants: {
      variant: "outlined",
      padding: "none",
    },
  },
);

export interface CardProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof cardVariants> {}

export const Card = React.forwardRef<HTMLDivElement, CardProps>(
  ({ className, variant, padding, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(cardVariants({ variant, padding }), className)}
      {...props}
    />
  ),
);
Card.displayName = "Card";

export const CardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("flex flex-col gap-1 p-5 pb-3", className)}
    {...props}
  />
));
CardHeader.displayName = "CardHeader";

export const CardTitle = React.forwardRef<
  HTMLHeadingElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn(
      "text-base font-semibold leading-tight m-0 text-zen-foreground",
      className,
    )}
    {...props}
  />
));
CardTitle.displayName = "CardTitle";

export const CardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p
    ref={ref}
    className={cn("text-sm text-zen-muted-fg m-0", className)}
    {...props}
  />
));
CardDescription.displayName = "CardDescription";

export const CardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-5 pt-0", className)} {...props} />
));
CardContent.displayName = "CardContent";

export const CardFooter = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "flex items-center gap-2 p-5 pt-3 border-t border-zen-border",
      className,
    )}
    {...props}
  />
));
CardFooter.displayName = "CardFooter";

export { cardVariants };
