// packages/react/src/components/divider/divider.tsx
import * as React from "react";
import * as SeparatorPrimitive from "@radix-ui/react-separator";
import { cn } from "../../lib/cn";

/**
 * Separator (formerly "Divider") — built on @radix-ui/react-separator.
 *
 * Horizontal or vertical line that semantically separates content.
 * Decorative by default (decorative=true) so screen readers skip it; pass
 * decorative={false} when the separation is meaningful for assistive tech.
 */

export type SeparatorProps = React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>;

const Separator = React.forwardRef<
  React.ElementRef<typeof SeparatorPrimitive.Root>,
  SeparatorProps
>(
  (
    { className, orientation = "horizontal", decorative = true, ...props },
    ref,
  ) => (
    <SeparatorPrimitive.Root
      ref={ref}
      decorative={decorative}
      orientation={orientation}
      className={cn(
        "zen-shrink-0 zen-bg-zen-border",
        orientation === "horizontal" ? "zen-h-px zen-w-full" : "zen-h-full zen-w-px",
        className,
      )}
      {...props}
    />
  ),
);
Separator.displayName = SeparatorPrimitive.Root.displayName;

export { Separator };

// packages/solid/src/components/divider/divider.tsx
import { type JSX, splitProps, mergeProps } from "solid-js";
import { cn } from "../../lib/cn";

/**
 * Separator — horizontal or vertical line that semantically separates
 * content. Decorative by default (screen readers skip it); pass
 * decorative={false} when the separation is meaningful for assistive tech.
 *
 * Implemented inline (one styled <div>) rather than via Kobalte, since
 * the markup is trivial and avoids pulling in a primitive for one
 * element.
 */

export type SeparatorProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "role"> & {
  orientation?: "horizontal" | "vertical";
  decorative?: boolean;
  class?: string;
};

export const Separator = (rawProps: SeparatorProps) => {
  const props = mergeProps(
    { orientation: "horizontal" as const, decorative: true },
    rawProps,
  );
  const [local, rest] = splitProps(props, ["orientation", "decorative", "class"]);
  return (
    <div
      role={local.decorative ? "none" : "separator"}
      aria-orientation={
        local.decorative ? undefined : local.orientation
      }
      data-orientation={local.orientation}
      class={cn(
        "zen-shrink-0 zen-bg-zen-border",
        local.orientation === "horizontal" ? "zen-h-px zen-w-full" : "zen-h-full zen-w-px",
        local.class,
      )}
      {...rest}
    />
  );
};
