// packages/solid/src/components/popover/popover.tsx
import { type JSX, splitProps } from "solid-js";
import { Popover as KPopover } from "@kobalte/core/popover";
import { cn } from "../../lib/cn";

/**
 * Popover — Solid port built on Kobalte Popover.
 *
 *   <Popover>
 *     <PopoverTrigger as={Button}>Open</PopoverTrigger>
 *     <PopoverContent>…</PopoverContent>
 *   </Popover>
 *
 * Kobalte supplies positioning (via @floating-ui), collision detection,
 * focus trap, click-outside dismissal, Escape-to-close, and ARIA.
 */

export const Popover = KPopover;
export const PopoverTrigger = KPopover.Trigger;
export const PopoverAnchor = KPopover.Anchor;
export const PopoverClose = KPopover.CloseButton;
export const PopoverPortal = KPopover.Portal;

export type PopoverContentProps = {
  class?: string;
  children?: JSX.Element;
};

export const PopoverContent = (props: PopoverContentProps) => {
  const [local] = splitProps(props, ["class", "children"]);
  return (
    <KPopover.Portal>
      <KPopover.Content
        class={cn(
          "zen-z-50 zen-w-72 zen-rounded-zen-md zen-border zen-border-zen-border zen-bg-zen-background zen-p-4 zen-text-zen-foreground zen-shadow-md zen-outline-none",
          local.class,
        )}
      >
        {local.children}
      </KPopover.Content>
    </KPopover.Portal>
  );
};

// packages/react/src/components/popover/popover.tsx
import * as React from "react";
import * as PopoverPrimitive from "@radix-ui/react-popover";
import { cn } from "../../lib/cn";

/**
 * Popover — built on @radix-ui/react-popover.
 *
 *   <Popover>
 *     <PopoverTrigger asChild><Button>Open</Button></PopoverTrigger>
 *     <PopoverContent>…</PopoverContent>
 *   </Popover>
 *
 * Radix supplies positioning, collision detection, focus trap, click-outside
 * dismissal, Escape-to-close, and ARIA.
 */

const Popover = PopoverPrimitive.Root;
const PopoverTrigger = PopoverPrimitive.Trigger;
const PopoverAnchor = PopoverPrimitive.Anchor;

const PopoverContent = React.forwardRef<
  React.ElementRef<typeof PopoverPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Content>
>(({ className, align = "center", sideOffset = 4, ...props }, ref) => (
  <PopoverPrimitive.Portal>
    <PopoverPrimitive.Content
      ref={ref}
      align={align}
      sideOffset={sideOffset}
      className={cn(
        "zen-z-50 zen-w-72 zen-rounded-zen-md zen-border zen-border-zen-border zen-bg-zen-background zen-p-4 zen-text-zen-foreground zen-shadow-md zen-outline-none",
        className,
      )}
      {...props}
    />
  </PopoverPrimitive.Portal>
));
PopoverContent.displayName = PopoverPrimitive.Content.displayName;

export { Popover, PopoverTrigger, PopoverContent, PopoverAnchor };
