// packages/solid/src/components/NewBoundFieldsDemo.tsx
import { createSignal, Show } from "solid-js";
import { createForm } from "@modular-forms/solid";
import {
  BoundCheckbox,
  BoundInput,
  BoundRadioGroup,
  BoundSelect,
  BoundSlider,
  BoundSwitch,
  BoundTextarea,
} from "./form-builder/bound-fields";
import { Button } from "./button/button";
import { DemoPage, DemoSection } from "./demo-helpers";

/**
 * This route used to render the whole Form demo inside itself, so it had no
 * code of its own and put a second <h1> and a nested demo page on the screen.
 * It now shows the adapters directly — the thing the route is named after.
 */
const NewBoundFieldsDemo = () => {
  // `any` for the same reason NewFormDemo does it: the demo does not carry a
  // generated Values type, and typing the store here would not make the
  // adapters any better checked.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [form, { Form: MForm, Field }] = createForm<any>();
  const [submitted, setSubmitted] = createSignal<string | null>(null);

  return (
    <DemoPage
      title="BoundFields"
      description={
        <>
          One line per field instead of five. Each <code>Bound*</code> adapter
          renders the label, the control and the error message from a single
          call, reading everything it needs out of the form store.
        </>
      }
    >
      <DemoSection
        title="1. What an adapter replaces"
        codeTitle="Label, control, error — from one line"
        codeDescription="Pass the form store as `of` and modular-forms' Field component as `Field`. The adapter reads field.error itself, so whatever validator you wire into createForm({ validate }) surfaces without any per-field plumbing. That is the whole trade: you give up direct control of the markup and get a form you can read."
        code={`const [form, { Form: MForm, Field }] = createForm<Values>();

<BoundInput of={form} Field={Field} name="email" label="Email" required />

// versus, by hand:
<Field name="email">
  {(field, props) => (
    <div>
      <label for="email">Email</label>
      <Input {...props} id="email" value={field.value} />
      <Show when={field.error}>{(e) => <p role="alert">{e()}</p>}</Show>
    </div>
  )}
</Field>`}
      >
        <MForm onSubmit={(v: unknown) => setSubmitted(JSON.stringify(v, null, 2))}>
          <div class="zen-flex zen-max-w-md zen-flex-col zen-gap-3">
            <BoundInput
              of={form}
              Field={Field}
              name="email"
              label="Email"
              type="email"
              required
              placeholder="ada@algorisys.com"
            />
            <BoundTextarea
              of={form}
              Field={Field}
              name="bio"
              label="Bio"
              description="A short tagline."
              rows={3}
            />
            <Button type="submit" size="sm">
              Submit
            </Button>
            <Show when={submitted()}>
              <pre class="zen-m-0 zen-overflow-x-auto zen-rounded-zen-sm zen-bg-zen-muted zen-p-3 zen-text-xs">
                {submitted()}
              </pre>
            </Show>
          </div>
        </MForm>
      </DemoSection>

      <DemoSection
        title="2. The full set"
        codeTitle="Seven adapters, one shape"
        codeDescription="Every adapter takes the same three props — of, Field, name — plus whatever its own control needs. BoundSelect takes options, BoundSlider takes min/max, and so on. The uniformity is the point: once you have written one you have written all of them, and a config-driven form can generate them from a schema."
        code={`<BoundInput      of={form} Field={Field} name="name"   label="Name" />
<BoundTextarea   of={form} Field={Field} name="bio"    label="Bio" rows={3} />
<BoundSelect     of={form} Field={Field} name="plan"   label="Plan"
                 options={[{ label: "Free", value: "free" }]} />
<BoundRadioGroup of={form} Field={Field} name="tier"   label="Tier"
                 options={[{ label: "Low", value: "low" }]} />
<BoundCheckbox   of={form} Field={Field} name="agree"  label="I agree" />
<BoundSwitch     of={form} Field={Field} name="notify" label="Notifications" />
<BoundSlider     of={form} Field={Field} name="volume" label="Volume" />`}
      >
        <div class="zen-flex zen-max-w-md zen-flex-col zen-gap-3">
          <BoundSelect
            of={form}
            Field={Field}
            name="plan"
            label="Plan"
            options={[
              { label: "Free", value: "free" },
              { label: "Pro", value: "pro" },
              { label: "Team", value: "team" },
            ]}
          />
          <BoundRadioGroup
            of={form}
            Field={Field}
            name="priority"
            label="Priority"
            options={[
              { label: "Low", value: "low" },
              { label: "Medium", value: "medium" },
              { label: "High", value: "high" },
            ]}
          />
          <BoundSlider of={form} Field={Field} name="volume" label="Volume" />
          <BoundSwitch of={form} Field={Field} name="notifications" label="Notifications" />
          <BoundCheckbox of={form} Field={Field} name="agree" label="I accept the terms" />
        </div>
      </DemoSection>

      <DemoSection
        title="3. Why the store is a prop"
        codeTitle="`of` and `Field`, rather than a context"
        codeDescription="modular-forms hands you the store and the Field component from createForm(); the adapters take both explicitly rather than reaching for a context. That keeps two forms on one page from interfering, and means an adapter works anywhere you can pass a value — including inside a table row or a dialog rendered through a portal, where a context provider would have to be threaded through by hand."
        code={`// Two independent forms on one page, no ambiguity about which store:
const [signUp, { Field: SignUpField }] = createForm<SignUpValues>();
const [invite, { Field: InviteField }] = createForm<InviteValues>();

<BoundInput of={signUp} Field={SignUpField} name="email" label="Email" />
<BoundInput of={invite} Field={InviteField} name="email" label="Invitee" />`}
      >
        <p class="zen-m-0 zen-text-sm zen-text-zen-muted-fg">
          The Form demo renders exactly this — two <code>createForm</code> stores
          side by side on one page.
        </p>
      </DemoSection>
    </DemoPage>
  );
};

export default NewBoundFieldsDemo;

// packages/react/src/components/NewBoundFieldsDemo.tsx
import { useForm, FormProvider } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

import {
  BoundCheckbox,
  BoundInput,
  BoundRadioGroup,
  BoundSelect,
  BoundSlider,
  BoundSwitch,
  BoundTextarea,
} from "./form-builder/bound-fields";
import { Button } from "./button/button";
import { CodeExample } from "./demo-helpers";

const schema = z.object({
  email: z.string().email("Enter a valid email"),
  bio: z.string().max(160, "Keep it under 160 characters").optional(),
  plan: z.enum(["free", "pro", "team"]),
  priority: z.enum(["low", "medium", "high"]),
  volume: z.tuple([z.number().min(0).max(100)]),
  notifications: z.boolean(),
  newsletter: z.boolean(),
  agree: z.boolean().refine((v) => v === true, {
    message: "You must accept the terms",
  }),
});

type Values = z.infer<typeof schema>;

const NewBoundFieldsDemo: React.FC = () => {
  const form = useForm<Values>({
    resolver: zodResolver(schema),
    defaultValues: {
      email: "",
      bio: "",
      plan: "free",
      priority: "medium",
      volume: [50],
      notifications: true,
      newsletter: false,
      agree: false,
    },
    mode: "onTouched",
  });

  const onSubmit = (values: Values) => {
    alert(JSON.stringify(values, null, 2));
  };

  return (
    <div className="demo-page">
      <h1>Bound* fields (config-driven shortcut)</h1>
      <p className="lede">
        Thin adapters over the compound Form primitives that read from{" "}
        <code>useFormContext()</code> and render label + control + error in
        one shot. Same react-hook-form + Zod underneath as{" "}
        <code>&lt;FormField&gt;</code>; less boilerplate per field. Useful
        when your form is generated from a JSON / config schema.
      </p>

      <section className="demo-section">
        <h2>1. Every Bound* field in one form</h2>
        <CodeExample
          title="Pass name, label, rules — no Controller boilerplate"
          description="Each Bound* reads register / control / formState from FormProvider. Compose with the existing Form / FormField primitives if you need fully custom layout."
          code={`<FormProvider {...form}>
  <form onSubmit={form.handleSubmit(onSubmit)}>
    <BoundInput        name="email"         label="Email" required rules={{ required: "Required" }} />
    <BoundSelect       name="plan"          label="Plan"  options={planOptions} />
    <BoundRadioGroup   name="priority"      label="Priority" options={priorityOpts} orientation="horizontal" />
    <BoundSlider       name="volume"        label="Volume" min={0} max={100} />
    <BoundTextarea     name="bio"           label="Bio" />
    <BoundSwitch       name="notifications" label="Email notifications" />
    <BoundCheckbox     name="newsletter"    label="Subscribe to newsletter" />
    <BoundCheckbox     name="agree"         label="I agree to the terms" rules={{ required: "Required" }} />
    <Button type="submit">Submit</Button>
  </form>
</FormProvider>`}
        >
          <FormProvider {...form}>
            <form
              onSubmit={form.handleSubmit(onSubmit)}
              style={{ display: "grid", gap: "1rem", maxWidth: 520 }}
            >
              <BoundInput
                name="email"
                label="Email"
                required
                placeholder="you@algorisys.com"
                description="We'll never share it."
              />
              <BoundSelect
                name="plan"
                label="Plan"
                options={[
                  { value: "free", label: "Free" },
                  { value: "pro", label: "Pro" },
                  { value: "team", label: "Team" },
                ]}
              />
              <BoundRadioGroup
                name="priority"
                label="Priority"
                orientation="horizontal"
                options={[
                  { value: "low", label: "Low" },
                  { value: "medium", label: "Medium" },
                  { value: "high", label: "High" },
                ]}
              />
              <BoundSlider
                name="volume"
                label="Notification volume"
                min={0}
                max={100}
              />
              <BoundTextarea
                name="bio"
                label="Bio"
                rows={3}
                description="160 characters max."
              />
              <BoundSwitch
                name="notifications"
                label="Email notifications"
                description="Send a Monday summary."
              />
              <BoundCheckbox
                name="newsletter"
                label="Subscribe to the Algorisys newsletter"
              />
              <BoundCheckbox name="agree" label="I agree to the terms" />
              <div style={{ display: "flex", gap: 8 }}>
                <Button type="submit">Submit</Button>
                <Button
                  type="button"
                  variant="outline"
                  color="neutral"
                  onClick={() => form.reset()}
                >
                  Reset
                </Button>
              </div>
            </form>
          </FormProvider>
        </CodeExample>
      </section>

      <section className="demo-section">
        <h2>2. When to use Bound* vs the compound API</h2>
        <CodeExample
          title="Two valid idioms — pick what fits the call site"
          code={`// Bound* — config-driven, dense, fastest to write
<BoundInput name="email" label="Email" required />

// Compound (FormField + Slot) — when you want custom layout / per-field markup
<FormField
  control={form.control}
  name="email"
  render={({ field }) => (
    <FormItem>
      <FormLabel>Email</FormLabel>
      <FormControl><Input type="email" {...field} /></FormControl>
      <FormMessage />
    </FormItem>
  )}
/>

Both wire to the same useForm() / FormProvider; mix freely in the same form.`}
        >
          <p style={{ color: "var(--zen-color-muted-fg)", fontSize: "0.8125rem", margin: 0 }}>
            See the code snippet for the rundown.
          </p>
        </CodeExample>
      </section>
    </div>
  );
};

export default NewBoundFieldsDemo;
