// packages/solid/src/components/NewFABDemo.tsx
import { createSignal, For, Show } from "solid-js";
import { FAB } from "./fab/fab";
import { Button } from "./button/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./dropdown-menu/dropdown-menu";
import { Icon } from "./icon/icon";
import { DemoPage, DemoSection } from "./demo-helpers";

const NewFABDemo = () => {
  const [showFixed, setShowFixed] = createSignal(false);
  const [last, setLast] = createSignal<string | null>(null);

  return (
    <DemoPage
      title="FAB"
      description={
        <>
          Fixed-position floating action button. Wraps <code>Button</code> with
          positioning and elevation — a circle in a corner of the viewport, for
          the one action a screen is really about.
        </>
      }
    >
      <DemoSection
        title="1. Inline preview"
        codeTitle="Toggle to mount the fixed-position FABs"
        codeDescription="A FAB is position: fixed, so it floats over the whole page rather than sitting in this example box. They are behind a toggle here to keep the docs page readable — turn it on and look at the corners of the viewport, not at this card."
        code={`<FAB aria-label="Add" iconLeft={<Icon name="plus" />} onClick={add} />
<FAB position="bottom-left" color="error"
     aria-label="Delete" iconLeft={<Icon name="trash" />} />`}
      >
        <div class="zen-flex zen-flex-col zen-gap-3">
          <div class="zen-flex zen-items-center zen-gap-3">
            <Button size="sm" onClick={() => setShowFixed((v) => !v)}>
              {showFixed() ? "Hide fixed FABs" : "Show fixed FABs"}
            </Button>
            <Show when={last()}>
              <span class="zen-text-sm zen-text-zen-muted-fg">clicked: {last()}</span>
            </Show>
          </div>
          <Show when={showFixed()}>
            <>
              <FAB
                position="bottom-right"
                color="primary"
                aria-label="Add"
                iconLeft={<Icon name="plus" size={20} />}
                onClick={() => setLast("primary / bottom-right")}
              />
              <FAB
                position="bottom-left"
                color="error"
                aria-label="Delete"
                iconLeft={<Icon name="trash" size={20} />}
                onClick={() => setLast("error / bottom-left")}
              />
            </>
          </Show>
        </div>
      </DemoSection>

      <DemoSection
        title="2. Position"
        codeTitle="Four corners"
        codeDescription="bottom-right is the default and the one to reach for — it is where a thumb rests on a phone. bottom-left suits right-to-left layouts or a screen whose right corner is already spoken for; the top positions are unusual and mostly exist for full-bleed layouts with no header."
        code={`<FAB position="bottom-right" />   // default
<FAB position="bottom-left" />
<FAB position="top-right" />
<FAB position="top-left" />`}
      >
        <p class="zen-m-0 zen-text-sm zen-text-zen-muted-fg">
          Use the toggle in section 1 to see two of these mounted at once, in
          opposite corners.
        </p>
      </DemoSection>

      <DemoSection
        title="3. Size and colour"
        codeTitle="Three sizes, and Button's colour scale"
        codeDescription="lg (56px) is the default and matches the platform conventions on both iOS and Android. md suits dense desktop tools; xl is for a genuinely primary action on a touch-first screen. Colour comes straight from Button, so a FAB cannot drift away from the rest of the buttons in your app."
        code={`<FAB size="md" />   // 48px
<FAB size="lg" />   // 56px — default
<FAB size="xl" />   // 64px

<FAB color="primary" />  // default
<FAB color="error" />`}
      >
        <div class="zen-flex zen-items-end zen-gap-6">
          <For each={["md", "lg", "xl"] as const}>
            {(size) => (
              <div class="zen-flex zen-flex-col zen-items-center zen-gap-1">
                {/* `position` omitted so these render inline, side by side, for
                    comparison — a fixed one would leave the card entirely. */}
                <FAB
                  size={size}
                  aria-label={`Size ${size}`}
                  iconLeft={<Icon name="plus" size={20} />}
                />
                <span class="zen-text-xs zen-text-zen-muted-fg">{size}</span>
              </div>
            )}
          </For>
        </div>
      </DemoSection>

      <DemoSection
        title="4. Speed dial"
        codeTitle="Compose with DropdownMenu rather than growing a prop"
        codeDescription="A FAB that opens a menu of actions is a DropdownMenu whose trigger happens to be a FAB. There is no `actions` prop, deliberately — the menu already exists, already handles keyboard and dismissal, and a second implementation inside FAB would be one more thing to keep in step."
        code={`<DropdownMenu>
  <DropdownMenuTrigger>
    <FAB aria-label="Actions" iconLeft={<Icon name="plus" />} />
  </DropdownMenuTrigger>
  <DropdownMenuContent>
    <DropdownMenuItem>New document</DropdownMenuItem>
    <DropdownMenuItem>Upload</DropdownMenuItem>
  </DropdownMenuContent>
</DropdownMenu>`}
      >
        <DropdownMenu>
          <DropdownMenuTrigger>
            <FAB aria-label="Actions" iconLeft={<Icon name="plus" size={20} />} />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem onSelect={() => setLast("New document")}>
              New document
            </DropdownMenuItem>
            <DropdownMenuItem onSelect={() => setLast("Upload")}>Upload</DropdownMenuItem>
            <DropdownMenuItem onSelect={() => setLast("Invite people")}>
              Invite people
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </DemoSection>
    </DemoPage>
  );
};

export default NewFABDemo;

// packages/react/src/components/NewFABDemo.tsx
import { useState } from "react";
import { FAB } from "./fab/fab";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./dropdown-menu/dropdown-menu";
import { CodeExample } from "./demo-helpers";

const NewFABDemo: React.FC = () => {
  const [showAll, setShowAll] = useState(false);

  return (
    <div className="demo-page">
      <h1>FAB (new — shadcn-style composition)</h1>
      <p className="lede">
        Fixed-position floating action button. Wraps the new{" "}
        <code>Button</code> with positioning + elevation. For multi-action
        speed-dial menus, compose <code>FAB</code> with{" "}
        <code>DropdownMenu</code>.
      </p>

      <section className="demo-section">
        <h2>1. Inline preview</h2>
        <p style={{ fontSize: "1.3rem", color: "var(--zen-color-muted-fg)", marginTop: -8 }}>
          The real FABs render <em>fixed-position</em> over the whole page;
          to keep this docs page tidy they're enabled via the toggle below.
        </p>
        <CodeExample
          title="Toggle to mount fixed-position FABs"
          code={`<FAB onClick={...} iconLeft={<PlusIcon />} />
<FAB position="bottom-left" color="error" iconLeft={<TrashIcon />} />`}
        >
          <button
            onClick={() => setShowAll((v) => !v)}
            style={{
              padding: "0.6rem 1.2rem",
              background: "var(--zen-color-primary)",
              color: "white",
              border: 0,
              borderRadius: 6,
              cursor: "pointer",
              fontSize: "1.3rem",
            }}
          >
            {showAll ? "Hide fixed FABs" : "Show fixed FABs"}
          </button>
          {showAll ? (
            <>
              <FAB
                position="bottom-right"
                color="primary"
                aria-label="Add"
                iconLeft={<PlusIcon />}
                onClick={() => alert("Primary action")}
              />
              <FAB
                position="bottom-left"
                color="error"
                aria-label="Delete"
                iconLeft={<TrashIcon />}
                onClick={() => alert("Delete action")}
              />
            </>
          ) : null}
        </CodeExample>
      </section>

      <section className="demo-section">
        <h2>2. Speed-dial via DropdownMenu</h2>
        <CodeExample
          title="Compose FAB with DropdownMenu for multi-action menus"
          code={`<DropdownMenu>
  <DropdownMenuTrigger asChild>
    <FAB iconLeft={<PlusIcon />} aria-label="Quick actions" />
  </DropdownMenuTrigger>
  <DropdownMenuContent side="top" align="end">
    <DropdownMenuItem>New document</DropdownMenuItem>
    <DropdownMenuItem>New folder</DropdownMenuItem>
    <DropdownMenuItem>Upload file</DropdownMenuItem>
  </DropdownMenuContent>
</DropdownMenu>`}
        >
          <div style={{ position: "relative", height: 120, width: "100%" }}>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <div style={{ position: "absolute", bottom: 0, right: 0 }}>
                  <FAB
                    iconLeft={<PlusIcon />}
                    aria-label="Quick actions"
                    /* override the fixed positioning so it stays inside the demo card */
                    className="!zen-static"
                  />
                </div>
              </DropdownMenuTrigger>
              <DropdownMenuContent side="top" align="end">
                <DropdownMenuItem>New document</DropdownMenuItem>
                <DropdownMenuItem>New folder</DropdownMenuItem>
                <DropdownMenuItem>Upload file</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </CodeExample>
      </section>

      <section className="demo-section">
        <h2>3. Sizes</h2>
        <CodeExample
          title="md · lg (default) · xl"
          code={`<FAB size="md" /> <FAB size="lg" /> <FAB size="xl" />`}
        >
          <div style={{ display: "flex", gap: 16, alignItems: "center" }}>
            {(["md", "lg", "xl"] as const).map((size) => (
              <FAB
                key={size}
                size={size}
                className="!zen-static"
                aria-label={`Size ${size}`}
                iconLeft={<PlusIcon />}
              />
            ))}
          </div>
        </CodeExample>
      </section>

      <section className="demo-section">
        <h2>4. Colors</h2>
        <CodeExample
          title="Any Button color works"
          code={`<FAB color="success" iconLeft={<CheckIcon />} />
<FAB color="error" iconLeft={<TrashIcon />} />
<FAB color="warning" iconLeft={<AlertIcon />} />`}
        >
          <div style={{ display: "flex", gap: 16 }}>
            <FAB color="primary" className="!zen-static" iconLeft={<PlusIcon />} aria-label="Add" />
            <FAB color="success" className="!zen-static" iconLeft={<CheckIcon />} aria-label="Confirm" />
            <FAB color="error" className="!zen-static" iconLeft={<TrashIcon />} aria-label="Delete" />
            <FAB color="warning" className="!zen-static" iconLeft={<AlertIcon />} aria-label="Alert" />
          </div>
        </CodeExample>
      </section>
    </div>
  );
};

const PlusIcon = () => (
  <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="12" y1="5" x2="12" y2="19" />
    <line x1="5" y1="12" x2="19" y2="12" />
  </svg>
);
const TrashIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="3 6 5 6 21 6" />
    <path d="M19 6l-2 14a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2L5 6" />
  </svg>
);
const CheckIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="20 6 9 17 4 12" />
  </svg>
);
const AlertIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
    <line x1="12" y1="9" x2="12" y2="13" />
    <line x1="12" y1="17" x2="12" y2="17" />
  </svg>
);

export default NewFABDemo;
