// packages/react/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import "./index.css";
// Design tokens (defines --zen-color-* / --zen-radius-* / --zen-shadow-* per
// data-theme). MUST load before any UnoCSS utility (bg-zen-*, text-zen-*, …)
// is evaluated, otherwise those classes resolve to var(--zen-color-…) → empty.
import "@algorisys/zen-ui-core/tokens.css";
import "@algorisys/zen-ui-core/preflight.css";
import App from "./App";
import { applyTheme, getInitialTheme } from "./lib/theme";
import "virtual:uno.css";

// Migrate the legacy localStorage key from the pre-rename era. Without
// this, a stored value from an old build would leave <html data-theme=…>
// on first paint pointing at a name the new tokens.css has no rule for →
// no --zen-color-* vars get defined → everything renders unstyled.
// Unknown values (including any retired theme names) fall back to default.
try {
  const legacyStored = window.localStorage.getItem("jet-theme");
  if (legacyStored !== null) {
    if (window.localStorage.getItem("zen-ui-theme") === null) {
      const valid = ["default", "zen-theme", "dark"];
      const migrated = valid.includes(legacyStored) ? legacyStored : "default";
      window.localStorage.setItem("zen-ui-theme", migrated);
    }
    window.localStorage.removeItem("jet-theme");
  }
} catch {
  // ignore quota / private-mode errors
}

// Apply the persisted theme BEFORE React renders to avoid a flash of default
// styling on first paint when the user has previously picked Zen or Dark.
applyTheme(getInitialTheme());

// vite.config.demo.ts serves the app under `base: '/builder/'`, so React Router
// needs the same basename to match routes correctly on direct visits / refreshes.
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter basename="/builder">
      <App />
    </BrowserRouter>
  </StrictMode>
);

// packages/solid/src/main.tsx
/* @refresh reload */
import { render } from "solid-js/web";

import "./index.css";
// Design tokens (defines --zen-color-* / --zen-radius-* / --zen-shadow-* per
// data-theme). MUST load before any UnoCSS utility (bg-zen-*, text-zen-*, …)
// is evaluated, otherwise those classes resolve to var(--zen-color-…) → empty.
import "@algorisys/zen-ui-core/tokens.css";
import "@algorisys/zen-ui-core/preflight.css";
import "virtual:uno.css";

import App from "./App";
import { applyTheme, getInitialTheme } from "./lib/theme";

// Apply the persisted theme BEFORE Solid renders to avoid a flash of
// default styling on first paint when the user has previously picked
// Zen or Dark. @solidjs/router will be wired in once there are multiple
// demo routes — mirroring the React side's BrowserRouter setup.
applyTheme(getInitialTheme());

const root = document.getElementById("root");
if (!root) throw new Error("#root not found");

render(() => <App />, root);
