// packages/react/src/components/skeleton/skeleton.tsx
import * as React from "react";
import { cn } from "../../lib/cn";

/**
 * Skeleton — shadcn-style. No Radix primitive — just an animated muted
 * box you size with utility classes. Use one per visual block while the
 * real content loads.
 *
 *   <Skeleton className="h-4 w-32" />
 *   <Skeleton className="h-12 w-12 rounded-zen-full" />
 */

export type SkeletonProps = React.HTMLAttributes<HTMLDivElement>;

const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn("zen-animate-pulse zen-rounded-zen-md zen-bg-zen-muted", className)}
      {...props}
    />
  ),
);
Skeleton.displayName = "Skeleton";

export { Skeleton };

// packages/solid/src/components/skeleton/skeleton.tsx
import { type JSX, splitProps } from "solid-js";
import { cn } from "../../lib/cn";

/**
 * Skeleton — shadcn-style placeholder. Just an animated muted box you
 * size with utility classes. One per visual block while real content
 * loads.
 *
 *   <Skeleton class="h-4 w-32" />
 *   <Skeleton class="h-12 w-12 rounded-zen-full" />
 */

export type SkeletonProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class"> & {
  class?: string;
};

export const Skeleton = (props: SkeletonProps) => {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div class={cn("zen-animate-pulse zen-rounded-zen-md zen-bg-zen-muted", local.class)} {...rest} />
  );
};
