// packages/solid/src/components/form/mask-input/mask-input.tsx
import { type JSX, createMemo, createSignal, splitProps } from "solid-js";
import {
  applyMask,
  extractRaw,
  isMaskComplete,
  maskSkeleton,
  maskSlotCount,
  type MaskRules,
} from "@algorisys/zen-ui-core/mask";
import { cn } from "../../../lib/cn";
import { Input } from "../input/input";

/**
 * MaskInput — one input, a fixed template, and characters that can only land
 * where they are allowed.
 *
 *   <MaskInput mask="99-9999" onValueChange={(masked, raw) => …} />
 *   <MaskInput mask="aa-99" />
 *   <MaskInput mask="+\9\1 99999 99999" />   // escaped dialling code
 *
 * Default symbols: `9` a digit, `a` a letter, `*` either. Anything else is a
 * literal. A backslash escapes the next character — the only way to write a
 * literal that collides with a rule symbol.
 *
 * The engine is in `@algorisys/zen-ui-core/mask`, shared with the React
 * binding, so the two cannot disagree about what a mask means. Only the
 * rendering is ported.
 *
 * `value` is the MASKED string, and it is PARTIAL — "12-3", never "12-3___".
 * See the React binding for why both.
 *
 * Mirrors the React binding's API.
 */

export type MaskInputProps = Omit<
  JSX.InputHTMLAttributes<HTMLInputElement>,
  "value" | "onChange" | "class"
> & {
  /** The template, e.g. "99-9999". */
  mask: string;
  /** Extra or overriding symbols. Merged with the defaults, not replacing them. */
  rules?: MaskRules;
  /** Builds the placeholder skeleton — "__-____". Default "_". */
  placeholderChar?: string;
  /** The masked value. Pass "" to clear. */
  value?: string;
  defaultValue?: string;
  /** (masked, raw, complete) — store whichever you need. */
  onValueChange?: (masked: string, raw: string, complete: boolean) => void;
  class?: string;
};

export const MaskInput = (props: MaskInputProps) => {
  const [local, rest] = splitProps(props, [
    "mask",
    "rules",
    "placeholderChar",
    "value",
    "defaultValue",
    "onValueChange",
    "placeholder",
    "onKeyDown",
    "class",
  ]);

  // Read once, on purpose: this is the uncontrolled seed, and it mirrors
  // React's lazy useState initializer. A mask that changes after mount is a
  // different field; the caller re-keys it or drives `value`.
  const [inner, setInner] = createSignal(
    // eslint-disable-next-line solid/reactivity
    applyMask(extractRaw(props.defaultValue ?? "", props.mask, props.rules), props.mask, props.rules),
  );
  const isControlled = () => local.value !== undefined;
  // A controlled caller can hand back anything; run it through the engine so
  // the field can never display something the mask would not have produced.
  const masked = createMemo(() =>
    isControlled()
      ? applyMask(extractRaw(local.value as string, local.mask, local.rules), local.mask, local.rules)
      : inner(),
  );

  const commitRaw = (el: HTMLInputElement, raw: string) => {
    const nextMasked = applyMask(raw, local.mask, local.rules);
    if (!isControlled()) setInner(nextMasked);
    local.onValueChange?.(nextMasked, raw, isMaskComplete(raw, local.mask, local.rules));

    // Force the DOM back to what the engine allows.
    //
    // A rejected keystroke produces the SAME masked value as before, so the
    // signal does not change, so Solid does not re-render, so the character
    // the mask just refused stays sitting in the field. Typing "abc" into an
    // uppercase-only mask left "abc" on screen while the value was "".
    //
    // React's controlled input restores this for us; Solid's binding is a
    // one-way reactive assignment and does not. Hence the explicit write —
    // this is the divergence, not the API.
    if (el.value !== nextMasked) el.value = nextMasked;
  };

  const commit = (el: HTMLInputElement, next: string) =>
    commitRaw(el, extractRaw(next, local.mask, local.rules));

  /**
   * An all-digit mask gets the numeric keypad on a phone. Anything with a
   * letter slot must not: numeric would leave the user unable to type the
   * letters their own mask demands.
   */
  const inputMode = createMemo<"numeric" | "text">(() =>
    maskSlotCount(local.mask, local.rules) > 0 &&
    extractRaw("a".repeat(64), local.mask, local.rules).length === 0
      ? "numeric"
      : "text",
  );

  return (
    <Input
      // Not type="tel" or similar: the mask decides what is allowed, and a
      // type that fights it (number strips leading zeros) would win.
      type="text"
      inputMode={inputMode()}
      value={masked()}
      // Re-formatting whatever the field ends up holding is what makes typing,
      // pasting and deleting all arrive here as one case.
      onInput={(e) => commit(e.currentTarget, e.currentTarget.value)}
      onKeyDown={(e) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (local.onKeyDown as any)?.(e);
        if (e.defaultPrevented) return;
        // Backspace deletes a DATA character, not whatever glyph happens to sit
        // before the caret. Left to the browser it deletes the trailing
        // literal, applyMask puts it straight back, and the field jams:
        // "+91 12345 " swallowed every backspace forever.
        if (e.key === "Backspace" && !e.altKey && !e.ctrlKey && !e.metaKey) {
          e.preventDefault();
          commitRaw(e.currentTarget, extractRaw(masked(), local.mask, local.rules).slice(0, -1));
        }
      }}
      placeholder={
        local.placeholder ?? maskSkeleton(local.mask, local.placeholderChar ?? "_", local.rules)
      }
      autocomplete="off"
      class={cn(local.class)}
      {...rest}
    />
  );
};

// packages/react/src/components/form/mask-input/mask-input.tsx
import * as React from "react";
import {
  applyMask,
  extractRaw,
  isMaskComplete,
  maskSkeleton,
  maskSlotCount,
  type MaskRules,
} from "@algorisys/zen-ui-core/mask";
import { cn } from "../../../lib/cn";
import { Input } from "../input/input";

/**
 * MaskInput — one input, a fixed template, and characters that can only land
 * where they are allowed.
 *
 *   <MaskInput mask="99-9999" onValueChange={(masked, raw) => …} />
 *   <MaskInput mask="aa-99" />
 *   <MaskInput mask="+\9\1 99999 99999" />   // escaped dialling code
 *
 * Default symbols: `9` a digit, `a` a letter, `*` either. Anything else is a
 * literal the user never types and never deletes. A backslash escapes the
 * next character, which is the only way to write a literal that collides with
 * a rule symbol — see the note in core/mask.ts.
 *
 * The engine is in `@algorisys/zen-ui-core/mask` so this and the Solid
 * binding cannot disagree about what a mask means.
 *
 * Two decisions worth knowing:
 *
 *   `value` is the MASKED string — "12-3456", what the input shows and what a
 *   native form would submit. onValueChange hands you the raw alongside it, so
 *   whichever you store, it is one destructure away. Making `value` the raw
 *   would mean the prop and the visible field never agree, which is a strange
 *   thing for something called an input.
 *
 *   The value is PARTIAL: it holds what has been typed, formatted — "12-3",
 *   never "12-3___". A skeleton baked into the value has to be parsed back out
 *   on every keystroke and fights the caret for no benefit. The skeleton is the
 *   placeholder, where it costs nothing.
 */

export interface MaskInputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "value" | "defaultValue" | "onChange"> {
  /** The template, e.g. "99-9999". */
  mask: string;
  /** Extra or overriding symbols. Merged with the defaults, not replacing them. */
  rules?: MaskRules;
  /** Builds the placeholder skeleton — "__-____". Default "_". */
  placeholderChar?: string;
  /** The masked value. Pass "" to clear. */
  value?: string;
  defaultValue?: string;
  /** (masked, raw, complete) — store whichever you need. */
  onValueChange?: (masked: string, raw: string, complete: boolean) => void;
  className?: string;
}

export const MaskInput = React.forwardRef<HTMLInputElement, MaskInputProps>(
  (
    {
      mask,
      rules,
      placeholderChar = "_",
      value: valueProp,
      defaultValue,
      onValueChange,
      placeholder,
      onKeyDown,
      className,
      ...props
    },
    ref,
  ) => {
    const [inner, setInner] = React.useState(() =>
      applyMask(extractRaw(defaultValue ?? "", mask, rules), mask, rules),
    );
    const isControlled = valueProp !== undefined;
    // A controlled caller can hand back anything; run it through the engine so
    // the field can never display something the mask would not have produced.
    const masked = isControlled ? applyMask(extractRaw(valueProp, mask, rules), mask, rules) : inner;

    const commitRaw = (raw: string) => {
      const nextMasked = applyMask(raw, mask, rules);
      if (!isControlled) setInner(nextMasked);
      onValueChange?.(nextMasked, raw, isMaskComplete(raw, mask, rules));
    };

    const commit = (next: string) => commitRaw(extractRaw(next, mask, rules));

    return (
      <Input
        ref={ref}
        // Not type="tel" or similar: the mask decides what is allowed, and a
        // type that fights it (number strips leading zeros) would win.
        type="text"
        inputMode={maskInputMode(mask, rules)}
        value={masked}
        // Re-formatting whatever the field ends up holding is what makes
        // typing, pasting and deleting all arrive here as one case. Anything
        // the mask rejects never reaches state, so it never renders.
        onChange={(e) => commit(e.target.value)}
        onKeyDown={(e) => {
          onKeyDown?.(e);
          if (e.defaultPrevented) return;
          // Backspace deletes a DATA character, not whatever glyph happens to
          // sit before the caret. Left to the browser it deletes the trailing
          // literal, applyMask puts it straight back, and the field jams:
          // "+91 12345 " swallowed every backspace forever. Literals are not
          // the user's to delete, so deleting through them is the only reading
          // that makes sense.
          if (e.key === "Backspace" && !e.altKey && !e.ctrlKey && !e.metaKey) {
            e.preventDefault();
            commitRaw(extractRaw(masked, mask, rules).slice(0, -1));
          }
        }}
        placeholder={placeholder ?? maskSkeleton(mask, placeholderChar, rules)}
        autoComplete="off"
        className={cn(className)}
        {...props}
      />
    );
  },
);
MaskInput.displayName = "MaskInput";

/**
 * An all-digit mask gets the numeric keypad on a phone. Anything with a letter
 * slot must not: `inputMode="numeric"` would leave the user unable to type the
 * letters their own mask demands.
 */
const maskInputMode = (mask: string, rules?: MaskRules): "numeric" | "text" =>
  maskSlotCount(mask, rules) > 0 && extractRaw("a".repeat(64), mask, rules).length === 0
    ? "numeric"
    : "text";
