// packages/solid/src/components/empty-state/empty-state.tsx
import { type JSX, splitProps } from "solid-js";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/cn";

/**
 * EmptyState — surface shown when a list / table / dashboard has no
 * data yet. Compound: Icon / Title / Description / Actions.
 *
 *   <EmptyState>
 *     <EmptyStateIcon><InboxIcon /></EmptyStateIcon>
 *     <EmptyStateTitle>No invoices yet</EmptyStateTitle>
 *     <EmptyStateDescription>
 *       Create your first invoice to track revenue.
 *     </EmptyStateDescription>
 *     <EmptyStateActions>
 *       <Button>Create invoice</Button>
 *     </EmptyStateActions>
 *   </EmptyState>
 */

const emptyStateVariants = cva(
  "zen-flex zen-flex-col zen-items-center zen-justify-center zen-text-center zen-text-zen-foreground",
  {
    variants: {
      size: {
        sm: "zen-py-6 zen-px-3 zen-gap-1.5",
        md: "zen-py-10 zen-px-6 zen-gap-3",
        lg: "zen-py-16 zen-px-8 zen-gap-4",
      },
      bordered: {
        true: "zen-border-2 zen-border-dashed zen-border-zen-border zen-rounded-zen-md zen-bg-zen-muted/40",
        false: "",
      },
    },
    defaultVariants: {
      size: "md",
      bordered: false,
    },
  },
);

export type EmptyStateProps = VariantProps<typeof emptyStateVariants> &
  Omit<JSX.HTMLAttributes<HTMLDivElement>, "class"> & {
    class?: string;
    children?: JSX.Element;
  };

export const EmptyState = (props: EmptyStateProps) => {
  const [local, rest] = splitProps(props, ["class", "size", "bordered", "children"]);
  return (
    <div
      role="status"
      class={cn(
        emptyStateVariants({ size: local.size, bordered: local.bordered }),
        local.class,
      )}
      {...rest}
    >
      {local.children}
    </div>
  );
};

type DivProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class"> & {
  class?: string;
  children?: JSX.Element;
};
type ParagraphProps = Omit<JSX.HTMLAttributes<HTMLParagraphElement>, "class"> & {
  class?: string;
  children?: JSX.Element;
};
type HeadingProps = Omit<JSX.HTMLAttributes<HTMLHeadingElement>, "class"> & {
  class?: string;
  children?: JSX.Element;
};

export const EmptyStateIcon = (props: DivProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div
      aria-hidden
      class={cn(
        "zen-inline-flex zen-items-center zen-justify-center",
        "zen-h-12 zen-w-12 zen-rounded-zen-full zen-bg-zen-muted zen-text-zen-muted-fg",
        "zen-mb-1",
        local.class,
      )}
      {...rest}
    >
      {local.children}
    </div>
  );
};

export const EmptyStateTitle = (props: HeadingProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <h3 class={cn("zen-text-base zen-font-semibold zen-m-0", local.class)} {...rest}>
      {local.children}
    </h3>
  );
};

export const EmptyStateDescription = (props: ParagraphProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <p
      class={cn(
        "zen-text-sm zen-text-zen-muted-fg zen-max-w-[40ch] zen-m-0 zen-leading-relaxed",
        local.class,
      )}
      {...rest}
    >
      {local.children}
    </p>
  );
};

export const EmptyStateActions = (props: DivProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div
      class={cn(
        "zen-flex zen-flex-wrap zen-items-center zen-justify-center zen-gap-2 zen-mt-2",
        local.class,
      )}
      {...rest}
    >
      {local.children}
    </div>
  );
};

export { emptyStateVariants };

// src/components/empty-state/empty-state.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/cn";

/**
 * EmptyState — surface shown when a list / table / dashboard has no
 * data yet. The first-run experience in any onboarding flow.
 *
 *   <EmptyState>
 *     <EmptyStateIcon><InboxIcon /></EmptyStateIcon>
 *     <EmptyStateTitle>No invoices yet</EmptyStateTitle>
 *     <EmptyStateDescription>
 *       Create your first invoice to track revenue.
 *     </EmptyStateDescription>
 *     <EmptyStateActions>
 *       <Button>Create invoice</Button>
 *       <Button variant="outline">Import from CSV</Button>
 *     </EmptyStateActions>
 *   </EmptyState>
 *
 * The default `size="md"` centers content with comfortable padding for
 * a card-sized container. Use `size="sm"` for inline empty states
 * (table body, dropdown menu) and `size="lg"` for full-page first-run
 * screens. `bordered` adds a dashed border + muted background to
 * communicate "drop something here" / "this is intentionally empty".
 */

const emptyStateVariants = cva(
  [
    "flex flex-col items-center justify-center text-center",
    "text-zen-foreground",
  ].join(" "),
  {
    variants: {
      size: {
        sm: "py-6 px-3 gap-1.5",
        md: "py-10 px-6 gap-3",
        lg: "py-16 px-8 gap-4",
      },
      bordered: {
        true: "border-2 border-dashed border-zen-border rounded-zen-md bg-zen-muted/40",
        false: "",
      },
    },
    defaultVariants: {
      size: "md",
      bordered: false,
    },
  },
);

export interface EmptyStateProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof emptyStateVariants> {}

export const EmptyState = React.forwardRef<HTMLDivElement, EmptyStateProps>(
  ({ className, size, bordered, ...props }, ref) => (
    <div
      ref={ref}
      role="status"
      className={cn(emptyStateVariants({ size, bordered }), className)}
      {...props}
    />
  ),
);
EmptyState.displayName = "EmptyState";

/**
 * Wraps the leading icon. Renders a muted circular tile around the
 * icon so an SVG passed as a child gets a consistent visual frame
 * without the caller needing to style the surface.
 */
export const EmptyStateIcon = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    aria-hidden
    className={cn(
      "inline-flex items-center justify-center",
      "h-12 w-12 rounded-zen-full bg-zen-muted text-zen-muted-fg",
      "mb-1",
      className,
    )}
    {...props}
  />
));
EmptyStateIcon.displayName = "EmptyStateIcon";

export const EmptyStateTitle = React.forwardRef<
  HTMLHeadingElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn("text-base font-semibold m-0", className)}
    {...props}
  />
));
EmptyStateTitle.displayName = "EmptyStateTitle";

export const EmptyStateDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p
    ref={ref}
    className={cn(
      "text-sm text-zen-muted-fg max-w-[40ch] m-0 leading-relaxed",
      className,
    )}
    {...props}
  />
));
EmptyStateDescription.displayName = "EmptyStateDescription";

export const EmptyStateActions = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "flex flex-wrap items-center justify-center gap-2 mt-2",
      className,
    )}
    {...props}
  />
));
EmptyStateActions.displayName = "EmptyStateActions";

export { emptyStateVariants };
