// packages/react/src/components/dialog/alert-dialog.tsx
import * as React from "react";
import * as AlertDialogPrimitive from "@radix-ui/react-alert-dialog";
import { cn } from "../../lib/cn";

/**
 * AlertDialog — destructive-confirm modal on @radix-ui/react-alert-dialog.
 *
 *   <AlertDialog>
 *     <AlertDialogTrigger asChild><Button color="error">Delete</Button></AlertDialogTrigger>
 *     <AlertDialogContent>
 *       <AlertDialogHeader>
 *         <AlertDialogTitle>Delete account?</AlertDialogTitle>
 *         <AlertDialogDescription>
 *           Removes all data permanently.
 *         </AlertDialogDescription>
 *       </AlertDialogHeader>
 *       <AlertDialogFooter>
 *         <AlertDialogCancel asChild><Button variant="ghost">Cancel</Button></AlertDialogCancel>
 *         <AlertDialogAction asChild><Button color="error">Delete</Button></AlertDialogAction>
 *       </AlertDialogFooter>
 *     </AlertDialogContent>
 *   </AlertDialog>
 *
 * Differs from Dialog: ALL dismissal except an explicit Action/Cancel
 * click is blocked. Escape still closes for keyboard a11y, but
 * click-outside does NOT. role="alertdialog" announces immediately.
 *
 * Use for irreversible / destructive confirmations. For generic modals
 * (forms, info dialogs) use Dialog.
 */

const AlertDialog = AlertDialogPrimitive.Root;
const AlertDialogTrigger = AlertDialogPrimitive.Trigger;
const AlertDialogPortal = AlertDialogPrimitive.Portal;

const AlertDialogOverlay = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Overlay>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Overlay
    ref={ref}
    className={cn("fixed inset-0 z-50 bg-black/50", className)}
    {...props}
  />
));
AlertDialogOverlay.displayName = AlertDialogPrimitive.Overlay.displayName;

const AlertDialogContent = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Content>
>(({ className, ...props }, ref) => (
  <AlertDialogPortal>
    <AlertDialogOverlay />
    <AlertDialogPrimitive.Content
      ref={ref}
      className={cn(
        "fixed left-1/2 top-1/2 z-50 -translate-x-1/2 -translate-y-1/2",
        "w-full max-w-lg max-h-[85vh] overflow-y-auto",
        "rounded-zen-md border border-zen-border bg-zen-background p-6 shadow-zen-lg",
        "focus:outline-none",
        className,
      )}
      {...props}
    />
  </AlertDialogPortal>
));
AlertDialogContent.displayName = AlertDialogPrimitive.Content.displayName;

const AlertDialogHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("flex flex-col gap-1 text-left mb-3", className)} {...props} />
);
AlertDialogHeader.displayName = "AlertDialogHeader";

const AlertDialogFooter = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={cn(
      "flex flex-col-reverse sm:flex-row sm:justify-end gap-2 mt-5",
      className,
    )}
    {...props}
  />
);
AlertDialogFooter.displayName = "AlertDialogFooter";

const AlertDialogTitle = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Title
    ref={ref}
    className={cn("text-lg font-semibold leading-tight text-zen-foreground", className)}
    {...props}
  />
));
AlertDialogTitle.displayName = AlertDialogPrimitive.Title.displayName;

const AlertDialogDescription = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Description
    ref={ref}
    className={cn("text-sm text-zen-muted-fg leading-snug", className)}
    {...props}
  />
));
AlertDialogDescription.displayName = AlertDialogPrimitive.Description.displayName;

const AlertDialogAction = AlertDialogPrimitive.Action;
const AlertDialogCancel = AlertDialogPrimitive.Cancel;

export {
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogPortal,
  AlertDialogOverlay,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
};

// packages/solid/src/components/dialog/alert-dialog.tsx
import { type JSX, splitProps } from "solid-js";
import { AlertDialog as KAlertDialog } from "@kobalte/core/alert-dialog";
import { cn } from "../../lib/cn";

/**
 * AlertDialog — destructive-confirm modal built on Kobalte AlertDialog.
 *
 *   <AlertDialog>
 *     <AlertDialogTrigger as={Button} color="error">Delete</AlertDialogTrigger>
 *     <AlertDialogContent>
 *       <AlertDialogHeader>
 *         <AlertDialogTitle>Delete account?</AlertDialogTitle>
 *         <AlertDialogDescription>Removes all data permanently.</AlertDialogDescription>
 *       </AlertDialogHeader>
 *       <AlertDialogFooter>
 *         <AlertDialogCancel as={Button} variant="ghost">Cancel</AlertDialogCancel>
 *         <Button color="error" onClick={onConfirm}>Delete</Button>
 *       </AlertDialogFooter>
 *     </AlertDialogContent>
 *   </AlertDialog>
 *
 * Differs from Dialog: click-outside is blocked. Escape still closes
 * for keyboard a11y. role="alertdialog" announces immediately.
 *
 * API delta from React binding: Kobalte unifies AlertDialog.Action and
 * AlertDialog.Cancel under CloseButton — use the Action label visually
 * but wire the destructive callback via your own onClick (the Cancel
 * affordance is what we expose as <AlertDialogCancel>).
 */

export const AlertDialog = KAlertDialog;
export const AlertDialogTrigger = KAlertDialog.Trigger;
export const AlertDialogPortal = KAlertDialog.Portal;
export const AlertDialogCancel = KAlertDialog.CloseButton;
export const AlertDialogAction = KAlertDialog.CloseButton;

type DivProps = {
  class?: string;
  children?: JSX.Element;
};

export const AlertDialogOverlay = (props: DivProps) => {
  const [local] = splitProps(props, ["class", "children"]);
  return (
    <KAlertDialog.Overlay class={cn("zen-fixed zen-inset-0 zen-z-50 zen-bg-black/50", local.class)}>
      {local.children}
    </KAlertDialog.Overlay>
  );
};

export type AlertDialogContentProps = {
  class?: string;
  children?: JSX.Element;
};

export const AlertDialogContent = (props: AlertDialogContentProps) => {
  const [local] = splitProps(props, ["class", "children"]);
  return (
    <KAlertDialog.Portal>
      <AlertDialogOverlay />
      <KAlertDialog.Content
        class={cn(
          "zen-fixed zen-left-1/2 zen-top-1/2 zen-z-50 -zen-translate-x-1/2 -zen-translate-y-1/2",
          "zen-w-full zen-max-w-lg zen-max-h-[85vh] zen-overflow-y-auto",
          "zen-rounded-zen-md zen-border zen-border-zen-border zen-bg-zen-background zen-p-6 zen-shadow-zen-lg",
          "focus:zen-outline-none",
          local.class,
        )}
      >
        {local.children}
      </KAlertDialog.Content>
    </KAlertDialog.Portal>
  );
};

export const AlertDialogHeader = (props: DivProps) => {
  const [local] = splitProps(props, ["class", "children"]);
  return (
    <div class={cn("zen-flex zen-flex-col zen-gap-1 zen-text-left zen-mb-3", local.class)}>
      {local.children}
    </div>
  );
};

export const AlertDialogFooter = (props: DivProps) => {
  const [local] = splitProps(props, ["class", "children"]);
  return (
    <div
      class={cn(
        "zen-flex zen-flex-col-reverse sm:zen-flex-row sm:zen-justify-end zen-gap-2 zen-mt-5",
        local.class,
      )}
    >
      {local.children}
    </div>
  );
};

export const AlertDialogTitle = (props: DivProps) => {
  const [local] = splitProps(props, ["class", "children"]);
  return (
    <KAlertDialog.Title
      class={cn(
        "zen-text-lg zen-font-semibold zen-leading-tight zen-text-zen-foreground",
        local.class,
      )}
    >
      {local.children}
    </KAlertDialog.Title>
  );
};

export const AlertDialogDescription = (props: DivProps) => {
  const [local] = splitProps(props, ["class", "children"]);
  return (
    <KAlertDialog.Description
      class={cn("zen-text-sm zen-text-zen-muted-fg zen-leading-snug", local.class)}
    >
      {local.children}
    </KAlertDialog.Description>
  );
};
