// src/components/file-upload/file-upload.tsx
import * as React from "react";
import { cn } from "../../lib/cn";
import { Button } from "../button/button";

/**
 * FileUpload — drag-and-drop zone wrapping a native <input type="file">.
 *
 *   <FileUpload
 *     accept="image/*,.pdf"
 *     multiple
 *     maxSize={5 * 1024 * 1024}                  // 5 MB
 *     value={files}
 *     onValueChange={setFiles}
 *     onError={(errors) => toast({ variant: "destructive", ... })}
 *   />
 *
 * No external dep. Keeps the underlying <input> in the DOM so it
 * participates in native form submission (`name` prop) and a11y
 * is announced correctly.
 *
 * Validation is opt-in:
 *   - `accept`   forwarded to the input + checked client-side
 *   - `maxSize`  rejects oversize files before they hit `value`
 *
 * Reports rejected files via `onError(rejections)` so consumers can
 * surface a toast / inline error.
 */

export interface FileRejection {
  file: File;
  /** "size" | "type" | "max-files" */
  reason: "size" | "type" | "max-files";
  message: string;
}

export interface FileUploadProps
  extends Omit<
    React.InputHTMLAttributes<HTMLInputElement>,
    "value" | "defaultValue" | "onChange" | "onError" | "type" | "size"
  > {
  /** Selected files (controlled). */
  value?: File[];
  defaultValue?: File[];
  onValueChange?: (files: File[]) => void;
  /** Fires for each batch of rejected files (size / type / count). */
  onError?: (rejections: FileRejection[]) => void;
  /** Max bytes per file. */
  maxSize?: number;
  /** Max total file count. Defaults to 1 unless `multiple` is true. */
  maxFiles?: number;
  multiple?: boolean;
  disabled?: boolean;
  /** Replace the default "Choose files / Drag & drop" copy. */
  label?: React.ReactNode;
  helperText?: React.ReactNode;
  /** Show the selected file list inline. Default true. */
  showFileList?: boolean;
  className?: string;
}

const formatBytes = (bytes: number): string => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
};

const matchesAccept = (file: File, accept: string | undefined): boolean => {
  if (!accept) return true;
  const tokens = accept
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  return tokens.some((token) => {
    if (token.startsWith(".")) {
      return file.name.toLowerCase().endsWith(token.toLowerCase());
    }
    if (token.endsWith("/*")) {
      const prefix = token.slice(0, -1); // "image/"
      return file.type.startsWith(prefix);
    }
    return file.type === token;
  });
};

const FileUpload = React.forwardRef<HTMLInputElement, FileUploadProps>(
  (
    {
      value,
      defaultValue,
      onValueChange,
      onError,
      maxSize,
      maxFiles,
      multiple = false,
      disabled,
      label,
      helperText,
      showFileList = true,
      accept,
      className,
      ...inputProps
    },
    forwardedRef,
  ) => {
    const [internal, setInternal] = React.useState<File[]>(defaultValue ?? []);
    const isControlled = value !== undefined;
    const files = isControlled ? (value as File[]) : internal;
    const inputRef = React.useRef<HTMLInputElement>(null);
    React.useImperativeHandle(forwardedRef, () => inputRef.current!);

    const [isOver, setIsOver] = React.useState(false);
    const effectiveMax = maxFiles ?? (multiple ? Infinity : 1);

    const validateAndSet = (next: FileList | File[]) => {
      const arr = Array.from(next);
      const rejected: FileRejection[] = [];
      const accepted: File[] = [];

      for (const f of arr) {
        if (typeof maxSize === "number" && f.size > maxSize) {
          rejected.push({
            file: f,
            reason: "size",
            message: `"${f.name}" exceeds ${formatBytes(maxSize)}`,
          });
          continue;
        }
        if (!matchesAccept(f, accept)) {
          rejected.push({
            file: f,
            reason: "type",
            message: `"${f.name}" is not an accepted file type`,
          });
          continue;
        }
        accepted.push(f);
      }

      // Combine with existing if multiple; else replace
      let nextFiles = multiple ? [...files, ...accepted] : accepted.slice(0, 1);
      if (nextFiles.length > effectiveMax) {
        const overflow = nextFiles.slice(effectiveMax);
        overflow.forEach((f) =>
          rejected.push({
            file: f,
            reason: "max-files",
            message: `Maximum ${effectiveMax} file(s); "${f.name}" dropped`,
          }),
        );
        nextFiles = nextFiles.slice(0, effectiveMax);
      }

      if (rejected.length > 0) onError?.(rejected);

      if (!isControlled) setInternal(nextFiles);
      onValueChange?.(nextFiles);
    };

    const removeFile = (idx: number) => {
      const next = files.filter((_, i) => i !== idx);
      if (!isControlled) setInternal(next);
      onValueChange?.(next);
    };

    const onDrop = (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      setIsOver(false);
      if (disabled) return;
      if (e.dataTransfer.files?.length) {
        validateAndSet(e.dataTransfer.files);
      }
    };

    return (
      <div className={cn("flex flex-col gap-2", className)}>
        <div
          onDragOver={(e) => {
            e.preventDefault();
            if (!disabled) setIsOver(true);
          }}
          onDragLeave={() => setIsOver(false)}
          onDrop={onDrop}
          onClick={() => !disabled && inputRef.current?.click()}
          role="button"
          tabIndex={disabled ? -1 : 0}
          aria-disabled={disabled || undefined}
          onKeyDown={(e) => {
            if (disabled) return;
            if (e.key === "Enter" || e.key === " ") {
              e.preventDefault();
              inputRef.current?.click();
            }
          }}
          className={cn(
            "rounded-zen-md border-2 border-dashed p-6 text-center transition-colors cursor-pointer",
            "flex flex-col items-center justify-center gap-2",
            isOver
              ? "border-zen-primary bg-zen-primary-soft"
              : "border-zen-border bg-zen-muted/30",
            "hover:bg-zen-muted/60",
            disabled && "opacity-50 cursor-not-allowed pointer-events-none",
            "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zen-ring focus-visible:ring-offset-2",
          )}
        >
          <UploadIcon />
          <div className="text-sm">
            {label ?? (
              <>
                <span className="font-medium">Click to upload</span>{" "}
                <span className="text-zen-muted-fg">or drag and drop</span>
              </>
            )}
          </div>
          {helperText ? (
            <div className="text-xs text-zen-muted-fg">{helperText}</div>
          ) : maxSize ? (
            <div className="text-xs text-zen-muted-fg">
              Max {formatBytes(maxSize)} per file
              {multiple && effectiveMax !== Infinity
                ? ` · up to ${effectiveMax} files`
                : ""}
            </div>
          ) : null}
          <input
            ref={inputRef}
            type="file"
            accept={accept}
            multiple={multiple}
            disabled={disabled}
            onChange={(e) => {
              if (e.target.files?.length) {
                validateAndSet(e.target.files);
              }
              // reset so the same file can be re-selected after removal
              e.target.value = "";
            }}
            className="sr-only"
            {...inputProps}
          />
        </div>

        {showFileList && files.length > 0 ? (
          <ul className="flex flex-col gap-1 text-sm">
            {files.map((file, idx) => (
              <li
                key={`${file.name}-${idx}`}
                className="flex items-center gap-3 rounded-zen-sm border border-zen-border bg-zen-background px-3 py-2"
              >
                <FileIcon />
                <div className="flex flex-col min-w-0 flex-1">
                  <span className="truncate font-medium">{file.name}</span>
                  <span className="text-xs text-zen-muted-fg">
                    {formatBytes(file.size)}
                  </span>
                </div>
                <Button
                  variant="ghost"
                  color="neutral"
                  size="sm"
                  aria-label={`Remove ${file.name}`}
                  onClick={(e) => {
                    e.stopPropagation();
                    removeFile(idx);
                  }}
                  disabled={disabled}
                >
                  <XIcon />
                </Button>
              </li>
            ))}
          </ul>
        ) : null}
      </div>
    );
  },
);
FileUpload.displayName = "FileUpload";

const UploadIcon = () => (
  <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden className="text-zen-muted-fg">
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="17 8 12 3 7 8" />
    <line x1="12" y1="3" x2="12" y2="15" />
  </svg>
);
const FileIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden className="text-zen-muted-fg shrink-0">
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
    <polyline points="14 2 14 8 20 8" />
  </svg>
);
const XIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

export { FileUpload };

// packages/solid/src/components/file-upload/file-upload.tsx
import { type JSX, createMemo, createSignal, For, Show } from "solid-js";
import { cn } from "../../lib/cn";
import { Button } from "../button/button";

/**
 * FileUpload — drag-and-drop zone wrapping a native <input type="file">.
 *
 *   <FileUpload
 *     accept="image/*,.pdf"
 *     multiple
 *     maxSize={5 * 1024 * 1024}
 *     value={files()}
 *     onValueChange={setFiles}
 *     onError={(errors) => toast.error(errors[0].message)}
 *   />
 *
 * No external dep. The underlying <input> stays in the DOM so it
 * participates in native form submission (`name` prop) and a11y. Reports
 * rejected files via `onError(rejections)`.
 */

export interface FileRejection {
  file: File;
  reason: "size" | "type" | "max-files";
  message: string;
}

export type FileUploadProps = {
  value?: File[];
  defaultValue?: File[];
  onValueChange?: (files: File[]) => void;
  onError?: (rejections: FileRejection[]) => void;
  maxSize?: number;
  maxFiles?: number;
  multiple?: boolean;
  disabled?: boolean;
  accept?: string;
  name?: string;
  label?: JSX.Element;
  helperText?: JSX.Element;
  showFileList?: boolean;
  class?: string;
};

const formatBytes = (bytes: number): string => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
};

const matchesAccept = (file: File, accept: string | undefined): boolean => {
  if (!accept) return true;
  const tokens = accept.split(",").map((s) => s.trim()).filter(Boolean);
  return tokens.some((token) => {
    if (token.startsWith(".")) return file.name.toLowerCase().endsWith(token.toLowerCase());
    if (token.endsWith("/*")) return file.type.startsWith(token.slice(0, -1));
    return file.type === token;
  });
};

export const FileUpload = (props: FileUploadProps) => {
  const isControlled = () => props.value !== undefined;
  const [inner, setInner] = createSignal<File[]>(props.defaultValue ?? []);
  const files = createMemo<File[]>(() => (isControlled() ? (props.value as File[]) : inner()));
  let inputRef: HTMLInputElement | undefined;
  const [isOver, setIsOver] = createSignal(false);
  const effectiveMax = () => props.maxFiles ?? (props.multiple ? Infinity : 1);
  const showFileList = () => props.showFileList ?? true;

  const validateAndSet = (next: FileList | File[]) => {
    const arr = Array.from(next);
    const rejected: FileRejection[] = [];
    const accepted: File[] = [];

    for (const f of arr) {
      if (typeof props.maxSize === "number" && f.size > props.maxSize) {
        rejected.push({ file: f, reason: "size", message: `"${f.name}" exceeds ${formatBytes(props.maxSize)}` });
        continue;
      }
      if (!matchesAccept(f, props.accept)) {
        rejected.push({ file: f, reason: "type", message: `"${f.name}" is not an accepted file type` });
        continue;
      }
      accepted.push(f);
    }

    let nextFiles = props.multiple ? [...files(), ...accepted] : accepted.slice(0, 1);
    const max = effectiveMax();
    if (nextFiles.length > max) {
      const overflow = nextFiles.slice(max);
      overflow.forEach((f) =>
        rejected.push({ file: f, reason: "max-files", message: `Maximum ${max} file(s); "${f.name}" dropped` }),
      );
      nextFiles = nextFiles.slice(0, max);
    }

    if (rejected.length > 0) props.onError?.(rejected);
    if (!isControlled()) setInner(nextFiles);
    props.onValueChange?.(nextFiles);
  };

  const removeFile = (idx: number) => {
    const next = files().filter((_, i) => i !== idx);
    if (!isControlled()) setInner(next);
    props.onValueChange?.(next);
  };

  const onDrop = (e: DragEvent) => {
    e.preventDefault();
    setIsOver(false);
    if (props.disabled) return;
    if (e.dataTransfer?.files?.length) validateAndSet(e.dataTransfer.files);
  };

  return (
    <div class={cn("flex flex-col gap-2", props.class)}>
      <div
        onDragOver={(e) => {
          e.preventDefault();
          if (!props.disabled) setIsOver(true);
        }}
        onDragLeave={() => setIsOver(false)}
        onDrop={onDrop}
        onClick={() => !props.disabled && inputRef?.click()}
        role="button"
        tabIndex={props.disabled ? -1 : 0}
        aria-disabled={props.disabled || undefined}
        onKeyDown={(e) => {
          if (props.disabled) return;
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            inputRef?.click();
          }
        }}
        class={cn(
          "rounded-zen-md border-2 border-dashed p-6 text-center transition-colors cursor-pointer",
          "flex flex-col items-center justify-center gap-2",
          isOver()
            ? "border-zen-primary bg-zen-primary-soft"
            : "border-zen-border bg-zen-muted/30",
          "hover:bg-zen-muted/60",
          props.disabled && "opacity-50 cursor-not-allowed pointer-events-none",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zen-ring focus-visible:ring-offset-2",
        )}
      >
        <UploadIcon />
        <div class="text-sm">
          {props.label ?? (
            <>
              <span class="font-medium">Click to upload</span>{" "}
              <span class="text-zen-muted-fg">or drag and drop</span>
            </>
          )}
        </div>
        <Show
          when={props.helperText}
          fallback={
            <Show when={props.maxSize}>
              <div class="text-xs text-zen-muted-fg">
                Max {formatBytes(props.maxSize as number)} per file
                {props.multiple && effectiveMax() !== Infinity
                  ? ` · up to ${effectiveMax()} files`
                  : ""}
              </div>
            </Show>
          }
        >
          <div class="text-xs text-zen-muted-fg">{props.helperText}</div>
        </Show>
        <input
          ref={inputRef}
          type="file"
          accept={props.accept}
          multiple={props.multiple}
          disabled={props.disabled}
          name={props.name}
          onChange={(e) => {
            if (e.currentTarget.files?.length) {
              validateAndSet(e.currentTarget.files);
            }
            e.currentTarget.value = "";
          }}
          class="sr-only"
        />
      </div>

      <Show when={showFileList() && files().length > 0}>
        <ul class="flex flex-col gap-1 text-sm">
          <For each={files()}>
            {(file, idx) => (
              <li class="flex items-center gap-3 rounded-zen-sm border border-zen-border bg-zen-background px-3 py-2">
                <FileIcon />
                <div class="flex flex-col min-w-0 flex-1">
                  <span class="truncate font-medium">{file.name}</span>
                  <span class="text-xs text-zen-muted-fg">{formatBytes(file.size)}</span>
                </div>
                <Button
                  variant="ghost"
                  color="neutral"
                  size="sm"
                  aria-label={`Remove ${file.name}`}
                  onClick={(e) => {
                    e.stopPropagation();
                    removeFile(idx());
                  }}
                  disabled={props.disabled}
                >
                  <XIcon />
                </Button>
              </li>
            )}
          </For>
        </ul>
      </Show>
    </div>
  );
};

const UploadIcon = () => (
  <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden class="text-zen-muted-fg">
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="17 8 12 3 7 8" />
    <line x1="12" y1="3" x2="12" y2="15" />
  </svg>
);
const FileIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden class="text-zen-muted-fg shrink-0">
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
    <polyline points="14 2 14 8 20 8" />
  </svg>
);
const XIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden>
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);
