// packages/solid/src/App.tsx
import { type Component, type ParentProps, ErrorBoundary, For, createSignal } from "solid-js";
import { A } from "@solidjs/router";
import { useTheme } from "./lib/theme";
import "./App.css";

/**
 * App shell — sticky header + collapsible sidebar + content area.
 * Mirrors the React demo's structure and CSS classes (see App.css,
 * copied verbatim from packages/react/src/App.css) so the two demos
 * read identically.
 *
 * Routes render inside an ErrorBoundary so a render-time crash in one
 * demo surfaces inline instead of silently leaving the content area
 * blank.
 */

type NavGroup = {
  group: string;
  items: { label: string; path: string }[];
};

const NAV: NavGroup[] = [
  {
    group: "Primitives",
    items: [
      { label: "Button", path: "/button" },
      { label: "Badge", path: "/badge" },
      { label: "Card", path: "/card" },
      { label: "Skeleton", path: "/skeleton" },
      { label: "Loading", path: "/loading" },
      { label: "FAB", path: "/fab" },
      { label: "Separator", path: "/separator" },
    ],
  },
  {
    group: "Surfaces",
    items: [
      { label: "Alert", path: "/alert" },
      { label: "Banner", path: "/banner" },
      { label: "EmptyState", path: "/empty-state" },
    ],
  },
  {
    group: "Flows",
    items: [{ label: "Stepper", path: "/stepper" }],
  },
  {
    group: "Survey",
    items: [
      { label: "Rating", path: "/rating" },
      { label: "NPS", path: "/nps" },
      { label: "Likert", path: "/likert" },
    ],
  },
  {
    group: "Display (Kobalte)",
    items: [
      { label: "Avatar", path: "/avatar" },
      { label: "Progress", path: "/progress" },
      { label: "Tooltip", path: "/tooltip" },
    ],
  },
  {
    group: "Form (Kobalte)",
    items: [
      { label: "Switch", path: "/switch" },
      { label: "Checkbox", path: "/checkbox" },
      { label: "RadioGroup", path: "/radio-group" },
      { label: "Slider", path: "/slider" },
      { label: "Select", path: "/select" },
    ],
  },
  {
    group: "Disclosure (Kobalte)",
    items: [
      { label: "Tabs", path: "/tabs" },
      { label: "Accordion", path: "/accordion" },
    ],
  },
  {
    group: "Overlays (Kobalte)",
    items: [
      { label: "Popover", path: "/popover" },
      { label: "Dialog", path: "/dialog" },
      { label: "Sheet", path: "/sheet" },
      { label: "DropdownMenu", path: "/dropdown-menu" },
      { label: "Toast", path: "/toast" },
    ],
  },
  {
    group: "Layout",
    items: [{ label: "ScrollArea", path: "/scroll-area" }],
  },
  {
    group: "Form (custom)",
    items: [
      { label: "Input", path: "/input" },
      { label: "NumberField", path: "/number-field" },
      { label: "TagInput", path: "/tag-input" },
      { label: "PhoneInput", path: "/phone-input" },
      { label: "InputOTP", path: "/otp" },
      { label: "FileUpload", path: "/file-upload" },
    ],
  },
  {
    group: "Data",
    items: [
      { label: "DataTable", path: "/data-table" },
      { label: "Combobox", path: "/combobox" },
      { label: "MultiCombobox", path: "/multi-combobox" },
      { label: "VirtualizedItems", path: "/lazy-options" },
    ],
  },
  {
    group: "Forms",
    items: [
      { label: "Form", path: "/form-new" },
      { label: "BoundFields", path: "/bound-fields" },
    ],
  },
  {
    group: "Date & time",
    items: [
      { label: "DatePicker", path: "/date-picker" },
      { label: "DateRangePicker", path: "/date-range-picker" },
      { label: "TimePicker", path: "/time-picker" },
      { label: "DateTimePicker", path: "/date-time-picker" },
    ],
  },
  {
    group: "Composite",
    items: [
      { label: "QRScanner", path: "/qr-scanner" },
      { label: "NotificationsInbox", path: "/notifications-inbox" },
    ],
  },
];

const MenuIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden>
    <line x1="3" y1="12" x2="21" y2="12" />
    <line x1="3" y1="6" x2="21" y2="6" />
    <line x1="3" y1="18" x2="21" y2="18" />
  </svg>
);

const RouteError = (props: { err: unknown; reset: () => void }) => (
  <div style={{ padding: "2.4rem", "max-width": "80rem", margin: "0 auto" }}>
    <div
      style={{
        background: "var(--zen-color-error-soft)",
        color: "var(--zen-color-error-soft-fg)",
        border: "1px solid var(--zen-color-error)",
        "border-radius": "0.6rem",
        padding: "1.6rem",
      }}
    >
      <h2 style={{ margin: "0 0 0.8rem", "font-size": "1.6rem" }}>
        Demo failed to render
      </h2>
      <p style={{ margin: "0 0 1rem", "font-size": "1.3rem" }}>
        {props.err instanceof Error ? props.err.message : String(props.err)}
      </p>
      <button
        onClick={props.reset}
        style={{
          padding: "0.6rem 1.2rem",
          "border-radius": "0.4rem",
          border: "1px solid var(--zen-color-error)",
          background: "transparent",
          color: "inherit",
          cursor: "pointer",
          "font-size": "1.3rem",
        }}
      >
        Retry
      </button>
      <details style={{ "margin-top": "1rem", "font-size": "1.2rem" }}>
        <summary style={{ cursor: "pointer" }}>Stack</summary>
        <pre style={{ overflow: "auto", "font-size": "1.1rem", "white-space": "pre-wrap" }}>
          {props.err instanceof Error ? props.err.stack : ""}
        </pre>
      </details>
    </div>
  </div>
);

const App: Component<ParentProps> = (props) => {
  const { theme, setTheme, themes } = useTheme();
  const [collapsed, setCollapsed] = createSignal(false);

  return (
    <div class="app-shell">
      <header class="app-header">
        <div class="app-header-left">
          <button
            type="button"
            class="sidebar-toggle"
            onClick={() => setCollapsed((v) => !v)}
            aria-label={collapsed() ? "Open sidebar" : "Close sidebar"}
          >
            <MenuIcon />
          </button>
          <div class="app-header-text">
            <h1 class="app-title">Zen UI · Solid</h1>
            <p class="app-subtitle">@algorisys/zen-ui-solid · component demo</p>
          </div>
        </div>
        <div class="app-header-actions">
          <label style={{
            display: "inline-flex",
            "align-items": "center",
            gap: "0.8rem",
            "font-size": "1.3rem",
            color: "var(--zen-color-muted-fg)",
          }}>
            Theme
            <select
              value={theme()}
              onChange={(e) => setTheme(e.currentTarget.value as never)}
              style={{
                padding: "0.5rem 0.8rem",
                "border-radius": "0.4rem",
                border: "1px solid var(--zen-color-border)",
                background: "var(--zen-color-background)",
                color: "var(--zen-color-foreground)",
                "font-size": "1.3rem",
                cursor: "pointer",
              }}
            >
              <For each={themes}>{(t) => <option value={t.name}>{t.label}</option>}</For>
            </select>
          </label>
        </div>
      </header>

      <div class="app-body">
        <aside class={`sidebar ${collapsed() ? "is-collapsed" : ""}`}>
          <nav>
            <For each={NAV}>
              {(group) => (
                <div class="sidebar-group">
                  <h3 class="sidebar-group-title">{group.group}</h3>
                  <ul class="sidebar-list">
                    <For each={group.items}>
                      {(item) => (
                        <li>
                          <A
                            href={item.path}
                            class="sidebar-link sidebar-link-inactive"
                            activeClass="sidebar-link sidebar-link-active"
                            inactiveClass="sidebar-link-inactive"
                            end
                          >
                            {item.label}
                          </A>
                        </li>
                      )}
                    </For>
                  </ul>
                </div>
              )}
            </For>
          </nav>
        </aside>
        <main class="app-content">
          <ErrorBoundary fallback={(err, reset) => <RouteError err={err} reset={reset} />}>
            {props.children}
          </ErrorBoundary>
        </main>
      </div>
    </div>
  );
};

export default App;

// src/App.tsx
import { useState } from "react";
import "./App.css";
import { NavLink, Routes, Route } from "react-router-dom";

import Welcome from "./components/Welcome";
import ThemeSwitcher from "./components/theme-switcher";

import NewButtonDemo from "./components/NewButtonDemo";
import NewTooltipDemo from "./components/NewTooltipDemo";
import NewDropdownMenuDemo from "./components/NewDropdownMenuDemo";
import NewSeparatorDemo from "./components/NewSeparatorDemo";
import NewSwitchDemo from "./components/NewSwitchDemo";
import NewCheckboxDemo from "./components/NewCheckboxDemo";
import NewRadioGroupDemo from "./components/NewRadioGroupDemo";
import NewProgressDemo from "./components/NewProgressDemo";
import NewAvatarDemo from "./components/NewAvatarDemo";
import NewBadgeDemo from "./components/NewBadgeDemo";
import NewSkeletonDemo from "./components/NewSkeletonDemo";
import NewLoadingDemo from "./components/NewLoadingDemo";
import NewSelectDemo from "./components/NewSelectDemo";
import NewSliderDemo from "./components/NewSliderDemo";
import NewScrollAreaDemo from "./components/NewScrollAreaDemo";
import NewInputDemo from "./components/NewInputDemo";
import NewNumberFieldDemo from "./components/NewNumberFieldDemo";
import NewDatePickerDemo from "./components/NewDatePickerDemo";
import NewOTPDemo from "./components/NewOTPDemo";
import NewPhoneInputDemo from "./components/NewPhoneInputDemo";
import NewFABDemo from "./components/NewFABDemo";
import NewFormDemo from "./components/NewFormDemo";
import NewDataTableDemo from "./components/NewDataTableDemo";
import NewLazyOptionsDemo from "./components/NewLazyOptionsDemo";
import NewComboboxDemo from "./components/NewComboboxDemo";
import NewAlertDemo from "./components/NewAlertDemo";
import NewDialogDemo from "./components/NewDialogDemo";
import NewToastDemo from "./components/NewToastDemo";
import NewFileUploadDemo from "./components/NewFileUploadDemo";
import NewBoundFieldsDemo from "./components/NewBoundFieldsDemo";
import NewStepperDemo from "./components/NewStepperDemo";
import NewBannerDemo from "./components/NewBannerDemo";
import NewEmptyStateDemo from "./components/NewEmptyStateDemo";
import NewTabsDemo from "./components/NewTabsDemo";
import NewAccordionDemo from "./components/NewAccordionDemo";
import NewCardDemo from "./components/NewCardDemo";
import NewSheetDemo from "./components/NewSheetDemo";
import NewDateRangePickerDemo from "./components/NewDateRangePickerDemo";
import NewTagInputDemo from "./components/NewTagInputDemo";
import NewMultiComboboxDemo from "./components/NewMultiComboboxDemo";
import NewRatingDemo from "./components/NewRatingDemo";
import NewNpsDemo from "./components/NewNpsDemo";
import NewLikertDemo from "./components/NewLikertDemo";
import NewTimePickerDemo from "./components/NewTimePickerDemo";
import { Toaster } from "./components/toast/toaster";

/**
 * Navigation data — single source of truth for the sidebar.
 * Add a new component's route here and it shows up under the right group.
 */
type NavEntry = { to: string; label: string };
type NavGroup = { title: string; items: NavEntry[] };

const NAV: NavGroup[] = [
  {
    title: "Getting started",
    items: [{ to: "/", label: "Welcome" }],
  },
  {
    title: "Components",
    items: [
      { to: "/button-new", label: "Button" },
      { to: "/tooltip-new", label: "Tooltip" },
      { to: "/dropdown-menu", label: "DropdownMenu" },
      { to: "/separator", label: "Separator" },
      { to: "/switch-new", label: "Switch" },
      { to: "/checkbox-new", label: "Checkbox" },
      { to: "/radio-group", label: "RadioGroup" },
      { to: "/progress-new", label: "Progress" },
      { to: "/avatar-new", label: "Avatar" },
      { to: "/badge-new", label: "Badge" },
      { to: "/skeleton-new", label: "Skeleton" },
      { to: "/loading-new", label: "Loading" },
      { to: "/select-new", label: "Select" },
      { to: "/slider-new", label: "Slider" },
      { to: "/scroll-area-new", label: "ScrollArea" },
      { to: "/input-new", label: "Input + Textarea" },
      { to: "/number-field-new", label: "NumberField" },
      { to: "/date-picker-new", label: "DatePicker" },
      { to: "/otp-new", label: "InputOTP" },
      { to: "/phone-input-new", label: "PhoneInput" },
      { to: "/fab-new", label: "FAB" },
      { to: "/form-new", label: "Form (RHF + Zod)" },
      { to: "/data-table", label: "DataTable" },
      { to: "/lazy-options", label: "Lazy options" },
      { to: "/combobox", label: "Combobox + Async" },
      { to: "/alert", label: "Alert" },
      { to: "/dialog", label: "Dialog + AlertDialog" },
      { to: "/toast", label: "Toast" },
      { to: "/file-upload", label: "FileUpload" },
      { to: "/form-bound", label: "Bound* fields" },
      { to: "/stepper", label: "Stepper" },
      { to: "/banner", label: "Banner" },
      { to: "/empty-state", label: "EmptyState" },
      { to: "/tabs", label: "Tabs" },
      { to: "/accordion", label: "Accordion" },
      { to: "/card", label: "Card" },
      { to: "/sheet", label: "Sheet / Drawer" },
      { to: "/date-range-picker", label: "DateRangePicker" },
      { to: "/tag-input", label: "TagInput" },
      { to: "/multi-combobox", label: "MultiCombobox" },
      { to: "/rating", label: "Rating" },
      { to: "/nps", label: "NPS" },
      { to: "/likert", label: "Likert" },
      { to: "/time-picker", label: "TimePicker" },
    ],
  },
];

const Sidebar: React.FC<{ collapsed: boolean }> = ({ collapsed }) => (
  <aside className={`sidebar${collapsed ? " is-collapsed" : ""}`} aria-hidden={collapsed}>
    {NAV.map((group) => (
      <div key={group.title} className="sidebar-group">
        <h4 className="sidebar-group-title">{group.title}</h4>
        <ul className="sidebar-list">
          {group.items.map((item) => (
            <li key={item.to}>
              <NavLink
                to={item.to}
                end={item.to === "/"}
                className={({ isActive }) =>
                  isActive
                    ? "sidebar-link sidebar-link-active"
                    : "sidebar-link sidebar-link-inactive"
                }
              >
                {item.label}
              </NavLink>
            </li>
          ))}
        </ul>
      </div>
    ))}
  </aside>
);

const SidebarToggle: React.FC<{
  collapsed: boolean;
  onToggle: () => void;
}> = ({ collapsed, onToggle }) => (
  <button
    type="button"
    className="sidebar-toggle"
    onClick={onToggle}
    aria-label={collapsed ? "Open sidebar" : "Close sidebar"}
    aria-expanded={!collapsed}
  >
    <svg
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <line x1="3" y1="6" x2="21" y2="6" />
      <line x1="3" y1="12" x2="21" y2="12" />
      <line x1="3" y1="18" x2="21" y2="18" />
    </svg>
  </button>
);

const SIDEBAR_KEY = "zen-sidebar-collapsed";

const App: React.FC = () => {
  const [collapsed, setCollapsed] = useState<boolean>(() => {
    if (typeof window === "undefined") return false;
    try {
      return window.localStorage.getItem(SIDEBAR_KEY) === "1";
    } catch {
      return false;
    }
  });
  const toggleSidebar = () => {
    setCollapsed((prev) => {
      const next = !prev;
      try {
        window.localStorage.setItem(SIDEBAR_KEY, next ? "1" : "0");
      } catch {
        /* ignore quota */
      }
      return next;
    });
  };

  return (
    <div className="app-shell">
      <header className="app-header">
        <div className="app-header-left">
          <SidebarToggle collapsed={collapsed} onToggle={toggleSidebar} />
          <div className="app-header-text">
            <h1 className="app-title">Zen UI Component Library</h1>
            <p className="app-subtitle">
              shadcn / Radix-style React component library by Algorisys.
            </p>
          </div>
        </div>
        <div className="app-header-actions">
          <ThemeSwitcher />
        </div>
      </header>
      <div className="app-body">
        <Sidebar collapsed={collapsed} />
        <main className="app-content">
          <Routes>
            <Route path="/" element={<Welcome />} />

            <Route path="/button-new" element={<NewButtonDemo />} />
            <Route path="/tooltip-new" element={<NewTooltipDemo />} />
            <Route path="/dropdown-menu" element={<NewDropdownMenuDemo />} />
            <Route path="/separator" element={<NewSeparatorDemo />} />
            <Route path="/switch-new" element={<NewSwitchDemo />} />
            <Route path="/checkbox-new" element={<NewCheckboxDemo />} />
            <Route path="/radio-group" element={<NewRadioGroupDemo />} />
            <Route path="/progress-new" element={<NewProgressDemo />} />
            <Route path="/avatar-new" element={<NewAvatarDemo />} />
            <Route path="/badge-new" element={<NewBadgeDemo />} />
            <Route path="/skeleton-new" element={<NewSkeletonDemo />} />
            <Route path="/loading-new" element={<NewLoadingDemo />} />
            <Route path="/select-new" element={<NewSelectDemo />} />
            <Route path="/slider-new" element={<NewSliderDemo />} />
            <Route path="/scroll-area-new" element={<NewScrollAreaDemo />} />
            <Route path="/input-new" element={<NewInputDemo />} />
            <Route path="/number-field-new" element={<NewNumberFieldDemo />} />
            <Route path="/date-picker-new" element={<NewDatePickerDemo />} />
            <Route path="/otp-new" element={<NewOTPDemo />} />
            <Route path="/phone-input-new" element={<NewPhoneInputDemo />} />
            <Route path="/fab-new" element={<NewFABDemo />} />
            <Route path="/form-new" element={<NewFormDemo />} />
            <Route path="/data-table" element={<NewDataTableDemo />} />
            <Route path="/lazy-options" element={<NewLazyOptionsDemo />} />
            <Route path="/combobox" element={<NewComboboxDemo />} />
            <Route path="/alert" element={<NewAlertDemo />} />
            <Route path="/dialog" element={<NewDialogDemo />} />
            <Route path="/toast" element={<NewToastDemo />} />
            <Route path="/file-upload" element={<NewFileUploadDemo />} />
            <Route path="/form-bound" element={<NewBoundFieldsDemo />} />
            <Route path="/stepper" element={<NewStepperDemo />} />
            <Route path="/banner" element={<NewBannerDemo />} />
            <Route path="/empty-state" element={<NewEmptyStateDemo />} />
            <Route path="/tabs" element={<NewTabsDemo />} />
            <Route path="/accordion" element={<NewAccordionDemo />} />
            <Route path="/card" element={<NewCardDemo />} />
            <Route path="/sheet" element={<NewSheetDemo />} />
            <Route path="/date-range-picker" element={<NewDateRangePickerDemo />} />
            <Route path="/tag-input" element={<NewTagInputDemo />} />
            <Route path="/multi-combobox" element={<NewMultiComboboxDemo />} />
            <Route path="/rating" element={<NewRatingDemo />} />
            <Route path="/nps" element={<NewNpsDemo />} />
            <Route path="/likert" element={<NewLikertDemo />} />
            <Route path="/time-picker" element={<NewTimePickerDemo />} />
          </Routes>
        </main>
      </div>
      {/* Mounted once near the root so toast({...}) can be called from
       * anywhere in the demo tree. */}
      <Toaster />
    </div>
  );
};

export default App;
