// packages/react/src/components/form/checkbox/checkbox.tsx
import * as React from "react";
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { cn } from "../../../lib/cn";

/**
 * Checkbox — built on @radix-ui/react-checkbox.
 *
 *   <Checkbox checked={value} onCheckedChange={setValue} />
 *   <Checkbox checked="indeterminate" onCheckedChange={setValue} />
 *
 * Radix supports the tri-state `"indeterminate"` natively (no DOM ref-poking
 * needed), keyboard activation (space), and ARIA. Themed via --zen-* tokens.
 */

export type CheckboxSize = "sm" | "md" | "lg";

export interface CheckboxProps
  extends React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root> {
  size?: CheckboxSize;
}

const BOX_SIZES: Record<CheckboxSize, string> = {
  sm: "h-3.5 w-3.5",
  md: "h-4 w-4",
  lg: "h-5 w-5",
};

const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  CheckboxProps
>(({ className, size = "md", ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      "peer shrink-0 rounded-zen-sm border border-zen-border bg-zen-background",
      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zen-ring focus-visible:ring-offset-2",
      "disabled:cursor-not-allowed disabled:opacity-50",
      "data-[state=checked]:bg-zen-primary data-[state=checked]:border-zen-primary data-[state=checked]:text-zen-primary-fg",
      "data-[state=indeterminate]:bg-zen-primary data-[state=indeterminate]:border-zen-primary data-[state=indeterminate]:text-zen-primary-fg",
      BOX_SIZES[size],
      className,
    )}
    {...props}
  >
    <CheckboxPrimitive.Indicator
      className={cn("flex items-center justify-center text-current")}
    >
      {props.checked === "indeterminate" ? (
        <DashIcon />
      ) : (
        <CheckIcon />
      )}
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
));
Checkbox.displayName = CheckboxPrimitive.Root.displayName;

const CheckIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" width="100%" height="100%">
    <polyline points="20 6 9 17 4 12" />
  </svg>
);
const DashIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" width="100%" height="100%">
    <line x1="6" y1="12" x2="18" y2="12" />
  </svg>
);

export { Checkbox };

// packages/solid/src/components/form/checkbox/checkbox.tsx
import { type JSX, splitProps, Show } from "solid-js";
import { Checkbox as KCheckbox } from "@kobalte/core/checkbox";
import { cn } from "../../../lib/cn";

/**
 * Checkbox — Solid port built on Kobalte's Checkbox primitive.
 *
 *   <Checkbox checked={value()} onChange={setValue} />
 *   <Checkbox indeterminate />
 *
 * Kobalte exposes both `checked` and `indeterminate` props natively (no
 * DOM ref-poking), keyboard activation (space), and ARIA. Themed via
 * --zen-* tokens.
 */

export type CheckboxSize = "sm" | "md" | "lg";

export type CheckboxProps = {
  size?: CheckboxSize;
  class?: string;
  checked?: boolean;
  defaultChecked?: boolean;
  indeterminate?: boolean;
  onChange?: (checked: boolean) => void;
  disabled?: boolean;
  required?: boolean;
  name?: string;
  value?: string;
  /** Optional inline label rendered to the right of the box. */
  label?: JSX.Element;
};

const BOX_SIZES: Record<CheckboxSize, string> = {
  sm: "zen-h-3.5 zen-w-3.5",
  md: "zen-h-4 zen-w-4",
  lg: "zen-h-5 zen-w-5",
};

export const Checkbox = (props: CheckboxProps) => {
  const [local] = splitProps(props, [
    "class",
    "size",
    "checked",
    "defaultChecked",
    "indeterminate",
    "onChange",
    "disabled",
    "required",
    "name",
    "value",
    "label",
  ]);
  return (
    <KCheckbox
      checked={local.checked}
      defaultChecked={local.defaultChecked}
      indeterminate={local.indeterminate}
      onChange={local.onChange}
      disabled={local.disabled}
      required={local.required}
      name={local.name}
      value={local.value}
      class={cn("zen-inline-flex zen-items-center zen-gap-2", local.class)}
    >
      <KCheckbox.Input class="zen-sr-only" />
      <KCheckbox.Control
        class={cn(
          "zen-peer zen-shrink-0 zen-rounded-zen-sm zen-border zen-border-zen-border zen-bg-zen-background",
          "focus-visible:zen-outline-none focus-visible:zen-ring-2 focus-visible:zen-ring-zen-ring focus-visible:zen-ring-offset-2",
          "data-[disabled]:zen-cursor-not-allowed data-[disabled]:zen-opacity-50",
          "data-[checked]:zen-bg-zen-primary data-[checked]:zen-border-zen-primary data-[checked]:zen-text-zen-primary-fg",
          "data-[indeterminate]:zen-bg-zen-primary data-[indeterminate]:zen-border-zen-primary data-[indeterminate]:zen-text-zen-primary-fg",
          BOX_SIZES[local.size ?? "md"],
        )}
      >
        <KCheckbox.Indicator class="zen-flex zen-items-center zen-justify-center zen-text-current zen-h-full zen-w-full">
          <Show when={local.indeterminate} fallback={<CheckIcon />}>
            <DashIcon />
          </Show>
        </KCheckbox.Indicator>
      </KCheckbox.Control>
      {local.label ? <KCheckbox.Label class="zen-text-sm">{local.label}</KCheckbox.Label> : null}
    </KCheckbox>
  );
};

const CheckIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" width="100%" height="100%">
    <polyline points="20 6 9 17 4 12" />
  </svg>
);
const DashIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" width="100%" height="100%">
    <line x1="6" y1="12" x2="18" y2="12" />
  </svg>
);
